// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: gym.proto

package com.example.gym.buddies.data.protos;

public final class GymProto {
  private GymProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  public interface GymOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.Gym)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    String getName();
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    com.google.protobuf.ByteString
        getNameBytes();

    /**
     * <code>string website = 3;</code>
     * @return The website.
     */
    String getWebsite();
    /**
     * <code>string website = 3;</code>
     * @return The bytes for website.
     */
    com.google.protobuf.ByteString
        getWebsiteBytes();

    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    java.util.List<Branch>
        getBranchesList();
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    Branch getBranches(int index);
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    int getBranchesCount();
  }
  /**
   * Protobuf type {@code gbuddy.Gym}
   */
  public  static final class Gym extends
      com.google.protobuf.GeneratedMessageLite<
          Gym, Gym.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.Gym)
      GymOrBuilder {
    private Gym() {
      name_ = "";
      website_ = "";
      branches_ = emptyProtobufList();
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int NAME_FIELD_NUMBER = 2;
    private String name_;
    /**
     * <code>string name = 2;</code>
     * @return The name.
     */
    @Override
    public String getName() {
      return name_;
    }
    /**
     * <code>string name = 2;</code>
     * @return The bytes for name.
     */
    @Override
    public com.google.protobuf.ByteString
        getNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(name_);
    }
    /**
     * <code>string name = 2;</code>
     * @param value The name to set.
     */
    private void setName(
        String value) {
      value.getClass();
  
      name_ = value;
    }
    /**
     * <code>string name = 2;</code>
     */
    private void clearName() {
      
      name_ = getDefaultInstance().getName();
    }
    /**
     * <code>string name = 2;</code>
     * @param value The bytes for name to set.
     */
    private void setNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      name_ = value.toStringUtf8();
      
    }

    public static final int WEBSITE_FIELD_NUMBER = 3;
    private String website_;
    /**
     * <code>string website = 3;</code>
     * @return The website.
     */
    @Override
    public String getWebsite() {
      return website_;
    }
    /**
     * <code>string website = 3;</code>
     * @return The bytes for website.
     */
    @Override
    public com.google.protobuf.ByteString
        getWebsiteBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(website_);
    }
    /**
     * <code>string website = 3;</code>
     * @param value The website to set.
     */
    private void setWebsite(
        String value) {
      value.getClass();
  
      website_ = value;
    }
    /**
     * <code>string website = 3;</code>
     */
    private void clearWebsite() {
      
      website_ = getDefaultInstance().getWebsite();
    }
    /**
     * <code>string website = 3;</code>
     * @param value The bytes for website to set.
     */
    private void setWebsiteBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      website_ = value.toStringUtf8();
      
    }

    public static final int BRANCHES_FIELD_NUMBER = 16;
    private com.google.protobuf.Internal.ProtobufList<Branch> branches_;
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    @Override
    public java.util.List<Branch> getBranchesList() {
      return branches_;
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    public java.util.List<? extends BranchOrBuilder>
        getBranchesOrBuilderList() {
      return branches_;
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    @Override
    public int getBranchesCount() {
      return branches_.size();
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    @Override
    public Branch getBranches(int index) {
      return branches_.get(index);
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    public BranchOrBuilder getBranchesOrBuilder(
        int index) {
      return branches_.get(index);
    }
    private void ensureBranchesIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Branch> tmp = branches_;
      if (!tmp.isModifiable()) {
        branches_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void setBranches(
        int index, Branch value) {
      value.getClass();
  ensureBranchesIsMutable();
      branches_.set(index, value);
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void addBranches(Branch value) {
      value.getClass();
  ensureBranchesIsMutable();
      branches_.add(value);
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void addBranches(
        int index, Branch value) {
      value.getClass();
  ensureBranchesIsMutable();
      branches_.add(index, value);
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void addAllBranches(
        Iterable<? extends Branch> values) {
      ensureBranchesIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, branches_);
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void clearBranches() {
      branches_ = emptyProtobufList();
    }
    /**
     * <code>repeated .gbuddy.Branch branches = 16;</code>
     */
    private void removeBranches(int index) {
      ensureBranchesIsMutable();
      branches_.remove(index);
    }

    public static Gym parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Gym parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Gym parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Gym parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Gym parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Gym parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Gym prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.Gym}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Gym, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.Gym)
        GymOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.GymProto.Gym.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>string name = 2;</code>
       * @return The name.
       */
      @Override
      public String getName() {
        return instance.getName();
      }
      /**
       * <code>string name = 2;</code>
       * @return The bytes for name.
       */
      @Override
      public com.google.protobuf.ByteString
          getNameBytes() {
        return instance.getNameBytes();
      }
      /**
       * <code>string name = 2;</code>
       * @param value The name to set.
       * @return This builder for chaining.
       */
      public Builder setName(
          String value) {
        copyOnWrite();
        instance.setName(value);
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearName() {
        copyOnWrite();
        instance.clearName();
        return this;
      }
      /**
       * <code>string name = 2;</code>
       * @param value The bytes for name to set.
       * @return This builder for chaining.
       */
      public Builder setNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setNameBytes(value);
        return this;
      }

      /**
       * <code>string website = 3;</code>
       * @return The website.
       */
      @Override
      public String getWebsite() {
        return instance.getWebsite();
      }
      /**
       * <code>string website = 3;</code>
       * @return The bytes for website.
       */
      @Override
      public com.google.protobuf.ByteString
          getWebsiteBytes() {
        return instance.getWebsiteBytes();
      }
      /**
       * <code>string website = 3;</code>
       * @param value The website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsite(
          String value) {
        copyOnWrite();
        instance.setWebsite(value);
        return this;
      }
      /**
       * <code>string website = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsite() {
        copyOnWrite();
        instance.clearWebsite();
        return this;
      }
      /**
       * <code>string website = 3;</code>
       * @param value The bytes for website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setWebsiteBytes(value);
        return this;
      }

      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      @Override
      public java.util.List<Branch> getBranchesList() {
        return java.util.Collections.unmodifiableList(
            instance.getBranchesList());
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      @Override
      public int getBranchesCount() {
        return instance.getBranchesCount();
      }/**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      @Override
      public Branch getBranches(int index) {
        return instance.getBranches(index);
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder setBranches(
          int index, Branch value) {
        copyOnWrite();
        instance.setBranches(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder setBranches(
          int index, Branch.Builder builderForValue) {
        copyOnWrite();
        instance.setBranches(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder addBranches(Branch value) {
        copyOnWrite();
        instance.addBranches(value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder addBranches(
          int index, Branch value) {
        copyOnWrite();
        instance.addBranches(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder addBranches(
          Branch.Builder builderForValue) {
        copyOnWrite();
        instance.addBranches(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder addBranches(
          int index, Branch.Builder builderForValue) {
        copyOnWrite();
        instance.addBranches(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder addAllBranches(
          Iterable<? extends Branch> values) {
        copyOnWrite();
        instance.addAllBranches(values);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder clearBranches() {
        copyOnWrite();
        instance.clearBranches();
        return this;
      }
      /**
       * <code>repeated .gbuddy.Branch branches = 16;</code>
       */
      public Builder removeBranches(int index) {
        copyOnWrite();
        instance.removeBranches(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.Gym)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Gym();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "id_",
              "name_",
              "website_",
              "branches_",
              Branch.class,
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0010\u0004\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0010\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Gym> parser = PARSER;
          if (parser == null) {
            synchronized (Gym.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Gym>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.Gym)
    private static final Gym DEFAULT_INSTANCE;
    static {
      Gym defaultInstance = new Gym();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Gym.class, defaultInstance);
    }

    public static Gym getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Gym> PARSER;

    public static com.google.protobuf.Parser<Gym> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BranchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.Branch)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>int32 gymId = 2;</code>
     * @return The gymId.
     */
    int getGymId();

    /**
     * <code>string locality = 3;</code>
     * @return The locality.
     */
    String getLocality();
    /**
     * <code>string locality = 3;</code>
     * @return The bytes for locality.
     */
    com.google.protobuf.ByteString
        getLocalityBytes();

    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    String getCity();
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>double latitude = 5;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 6;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>string contact = 16;</code>
     * @return The contact.
     */
    String getContact();
    /**
     * <code>string contact = 16;</code>
     * @return The bytes for contact.
     */
    com.google.protobuf.ByteString
        getContactBytes();
  }
  /**
   * Protobuf type {@code gbuddy.Branch}
   */
  public  static final class Branch extends
      com.google.protobuf.GeneratedMessageLite<
          Branch, Branch.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.Branch)
      BranchOrBuilder {
    private Branch() {
      locality_ = "";
      city_ = "";
      contact_ = "";
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int GYMID_FIELD_NUMBER = 2;
    private int gymId_;
    /**
     * <code>int32 gymId = 2;</code>
     * @return The gymId.
     */
    @Override
    public int getGymId() {
      return gymId_;
    }
    /**
     * <code>int32 gymId = 2;</code>
     * @param value The gymId to set.
     */
    private void setGymId(int value) {
      
      gymId_ = value;
    }
    /**
     * <code>int32 gymId = 2;</code>
     */
    private void clearGymId() {
      
      gymId_ = 0;
    }

    public static final int LOCALITY_FIELD_NUMBER = 3;
    private String locality_;
    /**
     * <code>string locality = 3;</code>
     * @return The locality.
     */
    @Override
    public String getLocality() {
      return locality_;
    }
    /**
     * <code>string locality = 3;</code>
     * @return The bytes for locality.
     */
    @Override
    public com.google.protobuf.ByteString
        getLocalityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(locality_);
    }
    /**
     * <code>string locality = 3;</code>
     * @param value The locality to set.
     */
    private void setLocality(
        String value) {
      value.getClass();
  
      locality_ = value;
    }
    /**
     * <code>string locality = 3;</code>
     */
    private void clearLocality() {
      
      locality_ = getDefaultInstance().getLocality();
    }
    /**
     * <code>string locality = 3;</code>
     * @param value The bytes for locality to set.
     */
    private void setLocalityBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      locality_ = value.toStringUtf8();
      
    }

    public static final int CITY_FIELD_NUMBER = 4;
    private String city_;
    /**
     * <code>string city = 4;</code>
     * @return The city.
     */
    @Override
    public String getCity() {
      return city_;
    }
    /**
     * <code>string city = 4;</code>
     * @return The bytes for city.
     */
    @Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(city_);
    }
    /**
     * <code>string city = 4;</code>
     * @param value The city to set.
     */
    private void setCity(
        String value) {
      value.getClass();
  
      city_ = value;
    }
    /**
     * <code>string city = 4;</code>
     */
    private void clearCity() {
      
      city_ = getDefaultInstance().getCity();
    }
    /**
     * <code>string city = 4;</code>
     * @param value The bytes for city to set.
     */
    private void setCityBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      city_ = value.toStringUtf8();
      
    }

    public static final int LATITUDE_FIELD_NUMBER = 5;
    private double latitude_;
    /**
     * <code>double latitude = 5;</code>
     * @return The latitude.
     */
    @Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 5;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 5;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 6;
    private double longitude_;
    /**
     * <code>double longitude = 6;</code>
     * @return The longitude.
     */
    @Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 6;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 6;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static final int CONTACT_FIELD_NUMBER = 16;
    private String contact_;
    /**
     * <code>string contact = 16;</code>
     * @return The contact.
     */
    @Override
    public String getContact() {
      return contact_;
    }
    /**
     * <code>string contact = 16;</code>
     * @return The bytes for contact.
     */
    @Override
    public com.google.protobuf.ByteString
        getContactBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contact_);
    }
    /**
     * <code>string contact = 16;</code>
     * @param value The contact to set.
     */
    private void setContact(
        String value) {
      value.getClass();
  
      contact_ = value;
    }
    /**
     * <code>string contact = 16;</code>
     */
    private void clearContact() {
      
      contact_ = getDefaultInstance().getContact();
    }
    /**
     * <code>string contact = 16;</code>
     * @param value The bytes for contact to set.
     */
    private void setContactBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      contact_ = value.toStringUtf8();
      
    }

    public static Branch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Branch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Branch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Branch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Branch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Branch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Branch prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.Branch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Branch, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.Branch)
        BranchOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.GymProto.Branch.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>int32 gymId = 2;</code>
       * @return The gymId.
       */
      @Override
      public int getGymId() {
        return instance.getGymId();
      }
      /**
       * <code>int32 gymId = 2;</code>
       * @param value The gymId to set.
       * @return This builder for chaining.
       */
      public Builder setGymId(int value) {
        copyOnWrite();
        instance.setGymId(value);
        return this;
      }
      /**
       * <code>int32 gymId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGymId() {
        copyOnWrite();
        instance.clearGymId();
        return this;
      }

      /**
       * <code>string locality = 3;</code>
       * @return The locality.
       */
      @Override
      public String getLocality() {
        return instance.getLocality();
      }
      /**
       * <code>string locality = 3;</code>
       * @return The bytes for locality.
       */
      @Override
      public com.google.protobuf.ByteString
          getLocalityBytes() {
        return instance.getLocalityBytes();
      }
      /**
       * <code>string locality = 3;</code>
       * @param value The locality to set.
       * @return This builder for chaining.
       */
      public Builder setLocality(
          String value) {
        copyOnWrite();
        instance.setLocality(value);
        return this;
      }
      /**
       * <code>string locality = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocality() {
        copyOnWrite();
        instance.clearLocality();
        return this;
      }
      /**
       * <code>string locality = 3;</code>
       * @param value The bytes for locality to set.
       * @return This builder for chaining.
       */
      public Builder setLocalityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocalityBytes(value);
        return this;
      }

      /**
       * <code>string city = 4;</code>
       * @return The city.
       */
      @Override
      public String getCity() {
        return instance.getCity();
      }
      /**
       * <code>string city = 4;</code>
       * @return The bytes for city.
       */
      @Override
      public com.google.protobuf.ByteString
          getCityBytes() {
        return instance.getCityBytes();
      }
      /**
       * <code>string city = 4;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          String value) {
        copyOnWrite();
        instance.setCity(value);
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        copyOnWrite();
        instance.clearCity();
        return this;
      }
      /**
       * <code>string city = 4;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCityBytes(value);
        return this;
      }

      /**
       * <code>double latitude = 5;</code>
       * @return The latitude.
       */
      @Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 5;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 6;</code>
       * @return The longitude.
       */
      @Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 6;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <code>string contact = 16;</code>
       * @return The contact.
       */
      @Override
      public String getContact() {
        return instance.getContact();
      }
      /**
       * <code>string contact = 16;</code>
       * @return The bytes for contact.
       */
      @Override
      public com.google.protobuf.ByteString
          getContactBytes() {
        return instance.getContactBytes();
      }
      /**
       * <code>string contact = 16;</code>
       * @param value The contact to set.
       * @return This builder for chaining.
       */
      public Builder setContact(
          String value) {
        copyOnWrite();
        instance.setContact(value);
        return this;
      }
      /**
       * <code>string contact = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearContact() {
        copyOnWrite();
        instance.clearContact();
        return this;
      }
      /**
       * <code>string contact = 16;</code>
       * @param value The bytes for contact to set.
       * @return This builder for chaining.
       */
      public Builder setContactBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContactBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.Branch)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Branch();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "id_",
              "gymId_",
              "locality_",
              "city_",
              "latitude_",
              "longitude_",
              "contact_",
            };
            String info =
                "\u0000\u0007\u0000\u0000\u0001\u0010\u0007\u0000\u0000\u0000\u0001\u0004\u0002\u0004" +
                "\u0003\u0208\u0004\u0208\u0005\u0000\u0006\u0000\u0010\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Branch> parser = PARSER;
          if (parser == null) {
            synchronized (Branch.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Branch>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.Branch)
    private static final Branch DEFAULT_INSTANCE;
    static {
      Branch defaultInstance = new Branch();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Branch.class, defaultInstance);
    }

    public static Branch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Branch> PARSER;

    public static com.google.protobuf.Parser<Branch> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface RegisterResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.RegisterResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code gbuddy.RegisterResponse}
   */
  public  static final class RegisterResponse extends
      com.google.protobuf.GeneratedMessageLite<
          RegisterResponse, RegisterResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.RegisterResponse)
      RegisterResponseOrBuilder {
    private RegisterResponse() {
      message_ = "";
    }
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 16;
    private String message_;
    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 16;</code>
     * @param value The message to set.
     */
    private void setMessage(
        String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 16;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 16;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static RegisterResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static RegisterResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static RegisterResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RegisterResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RegisterResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static RegisterResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static RegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static RegisterResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(RegisterResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.RegisterResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          RegisterResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.RegisterResponse)
        RegisterResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.GymProto.RegisterResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 responseCode = 1;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string message = 16;</code>
       * @return The message.
       */
      @Override
      public String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 16;</code>
       * @return The bytes for message.
       */
      @Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 16;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.RegisterResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new RegisterResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "responseCode_",
              "message_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0010\u0002\u0000\u0000\u0000\u0001\u0004\u0010\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<RegisterResponse> parser = PARSER;
          if (parser == null) {
            synchronized (RegisterResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<RegisterResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.RegisterResponse)
    private static final RegisterResponse DEFAULT_INSTANCE;
    static {
      RegisterResponse defaultInstance = new RegisterResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        RegisterResponse.class, defaultInstance);
    }

    public static RegisterResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<RegisterResponse> PARSER;

    public static com.google.protobuf.Parser<RegisterResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface FetchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.FetchResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    java.util.List<Gym>
        getGymList();
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    Gym getGym(int index);
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    int getGymCount();
  }
  /**
   * Protobuf type {@code gbuddy.FetchResponse}
   */
  public  static final class FetchResponse extends
      com.google.protobuf.GeneratedMessageLite<
          FetchResponse, FetchResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.FetchResponse)
      FetchResponseOrBuilder {
    private FetchResponse() {
      message_ = "";
      gym_ = emptyProtobufList();
    }
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 16;
    private String message_;
    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 16;</code>
     * @param value The message to set.
     */
    private void setMessage(
        String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 16;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 16;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static final int GYM_FIELD_NUMBER = 17;
    private com.google.protobuf.Internal.ProtobufList<Gym> gym_;
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    @Override
    public java.util.List<Gym> getGymList() {
      return gym_;
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    public java.util.List<? extends GymOrBuilder>
        getGymOrBuilderList() {
      return gym_;
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    @Override
    public int getGymCount() {
      return gym_.size();
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    @Override
    public Gym getGym(int index) {
      return gym_.get(index);
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    public GymOrBuilder getGymOrBuilder(
        int index) {
      return gym_.get(index);
    }
    private void ensureGymIsMutable() {
      com.google.protobuf.Internal.ProtobufList<Gym> tmp = gym_;
      if (!tmp.isModifiable()) {
        gym_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void setGym(
        int index, Gym value) {
      value.getClass();
  ensureGymIsMutable();
      gym_.set(index, value);
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void addGym(Gym value) {
      value.getClass();
  ensureGymIsMutable();
      gym_.add(value);
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void addGym(
        int index, Gym value) {
      value.getClass();
  ensureGymIsMutable();
      gym_.add(index, value);
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void addAllGym(
        Iterable<? extends Gym> values) {
      ensureGymIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, gym_);
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void clearGym() {
      gym_ = emptyProtobufList();
    }
    /**
     * <code>repeated .gbuddy.Gym gym = 17;</code>
     */
    private void removeGym(int index) {
      ensureGymIsMutable();
      gym_.remove(index);
    }

    public static FetchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FetchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FetchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FetchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FetchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static FetchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static FetchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FetchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FetchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static FetchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static FetchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static FetchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(FetchResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.FetchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          FetchResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.FetchResponse)
        FetchResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.GymProto.FetchResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 responseCode = 1;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string message = 16;</code>
       * @return The message.
       */
      @Override
      public String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 16;</code>
       * @return The bytes for message.
       */
      @Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 16;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      @Override
      public java.util.List<Gym> getGymList() {
        return java.util.Collections.unmodifiableList(
            instance.getGymList());
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      @Override
      public int getGymCount() {
        return instance.getGymCount();
      }/**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      @Override
      public Gym getGym(int index) {
        return instance.getGym(index);
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder setGym(
          int index, Gym value) {
        copyOnWrite();
        instance.setGym(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder setGym(
          int index, Gym.Builder builderForValue) {
        copyOnWrite();
        instance.setGym(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder addGym(Gym value) {
        copyOnWrite();
        instance.addGym(value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder addGym(
          int index, Gym value) {
        copyOnWrite();
        instance.addGym(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder addGym(
          Gym.Builder builderForValue) {
        copyOnWrite();
        instance.addGym(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder addGym(
          int index, Gym.Builder builderForValue) {
        copyOnWrite();
        instance.addGym(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder addAllGym(
          Iterable<? extends Gym> values) {
        copyOnWrite();
        instance.addAllGym(values);
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder clearGym() {
        copyOnWrite();
        instance.clearGym();
        return this;
      }
      /**
       * <code>repeated .gbuddy.Gym gym = 17;</code>
       */
      public Builder removeGym(int index) {
        copyOnWrite();
        instance.removeGym(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.FetchResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new FetchResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "responseCode_",
              "message_",
              "gym_",
              Gym.class,
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0011\u0003\u0000\u0001\u0000\u0001\u0004\u0010\u0208" +
                "\u0011\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<FetchResponse> parser = PARSER;
          if (parser == null) {
            synchronized (FetchResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<FetchResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.FetchResponse)
    private static final FetchResponse DEFAULT_INSTANCE;
    static {
      FetchResponse defaultInstance = new FetchResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        FetchResponse.class, defaultInstance);
    }

    public static FetchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<FetchResponse> PARSER;

    public static com.google.protobuf.Parser<FetchResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface CoordinateResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.CoordinateResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>int32 responseCode = 3;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code gbuddy.CoordinateResponse}
   */
  public  static final class CoordinateResponse extends
      com.google.protobuf.GeneratedMessageLite<
          CoordinateResponse, CoordinateResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.CoordinateResponse)
      CoordinateResponseOrBuilder {
    private CoordinateResponse() {
      message_ = "";
    }
    public static final int LATITUDE_FIELD_NUMBER = 1;
    private double latitude_;
    /**
     * <code>double latitude = 1;</code>
     * @return The latitude.
     */
    @Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 1;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 1;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 2;
    private double longitude_;
    /**
     * <code>double longitude = 2;</code>
     * @return The longitude.
     */
    @Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 2;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 2;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 3;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 3;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 3;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 3;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 16;
    private String message_;
    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 16;</code>
     * @param value The message to set.
     */
    private void setMessage(
        String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 16;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 16;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static CoordinateResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CoordinateResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CoordinateResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CoordinateResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CoordinateResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static CoordinateResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static CoordinateResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CoordinateResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CoordinateResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static CoordinateResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static CoordinateResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static CoordinateResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(CoordinateResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.CoordinateResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          CoordinateResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.CoordinateResponse)
        CoordinateResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.GymProto.CoordinateResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>double latitude = 1;</code>
       * @return The latitude.
       */
      @Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 1;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 2;</code>
       * @return The longitude.
       */
      @Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 2;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <code>int32 responseCode = 3;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 3;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string message = 16;</code>
       * @return The message.
       */
      @Override
      public String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 16;</code>
       * @return The bytes for message.
       */
      @Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 16;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.CoordinateResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new CoordinateResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "latitude_",
              "longitude_",
              "responseCode_",
              "message_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0010\u0004\u0000\u0000\u0000\u0001\u0000\u0002\u0000" +
                "\u0003\u0004\u0010\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<CoordinateResponse> parser = PARSER;
          if (parser == null) {
            synchronized (CoordinateResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<CoordinateResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.CoordinateResponse)
    private static final CoordinateResponse DEFAULT_INSTANCE;
    static {
      CoordinateResponse defaultInstance = new CoordinateResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        CoordinateResponse.class, defaultInstance);
    }

    public static CoordinateResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<CoordinateResponse> PARSER;

    public static com.google.protobuf.Parser<CoordinateResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
