// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: loginsignup.proto

package com.example.gym.buddies.data.protos;

public final class LoginSignupProto {
  private LoginSignupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code gbuddy.RoleType}
   */
  public enum RoleType
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>APP_USER = 0;</code>
     */
    APP_USER(0),
    /**
     * <code>GYM_ADMIN = 1;</code>
     */
    GYM_ADMIN(1),
    /**
     * <code>APP_ADMIN = 2;</code>
     */
    APP_ADMIN(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>APP_USER = 0;</code>
     */
    public static final int APP_USER_VALUE = 0;
    /**
     * <code>GYM_ADMIN = 1;</code>
     */
    public static final int GYM_ADMIN_VALUE = 1;
    /**
     * <code>APP_ADMIN = 2;</code>
     */
    public static final int APP_ADMIN_VALUE = 2;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static RoleType valueOf(int value) {
      return forNumber(value);
    }

    public static RoleType forNumber(int value) {
      switch (value) {
        case 0: return APP_USER;
        case 1: return GYM_ADMIN;
        case 2: return APP_ADMIN;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<RoleType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        RoleType> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<RoleType>() {
            @Override
            public RoleType findValueByNumber(int number) {
              return RoleType.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return RoleTypeVerifier.INSTANCE;
    }

    private static final class RoleTypeVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new RoleTypeVerifier();
            @Override
            public boolean isInRange(int number) {
              return RoleType.forNumber(number) != null;
            }
          };

    private final int value;

    private RoleType(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gbuddy.RoleType)
  }

  public interface LoginRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.LoginRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    String getUsername();
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    com.google.protobuf.ByteString
        getUsernameBytes();

    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    String getPassword();
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();
  }
  /**
   * Protobuf type {@code gbuddy.LoginRequest}
   */
  public  static final class LoginRequest extends
      com.google.protobuf.GeneratedMessageLite<
          LoginRequest, LoginRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.LoginRequest)
      LoginRequestOrBuilder {
    private LoginRequest() {
      username_ = "";
      password_ = "";
    }
    public static final int USERNAME_FIELD_NUMBER = 1;
    private String username_;
    /**
     * <code>string username = 1;</code>
     * @return The username.
     */
    @Override
    public String getUsername() {
      return username_;
    }
    /**
     * <code>string username = 1;</code>
     * @return The bytes for username.
     */
    @Override
    public com.google.protobuf.ByteString
        getUsernameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(username_);
    }
    /**
     * <code>string username = 1;</code>
     * @param value The username to set.
     */
    private void setUsername(
        String value) {
      value.getClass();
  
      username_ = value;
    }
    /**
     * <code>string username = 1;</code>
     */
    private void clearUsername() {
      
      username_ = getDefaultInstance().getUsername();
    }
    /**
     * <code>string username = 1;</code>
     * @param value The bytes for username to set.
     */
    private void setUsernameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      username_ = value.toStringUtf8();
      
    }

    public static final int PASSWORD_FIELD_NUMBER = 2;
    private String password_;
    /**
     * <code>string password = 2;</code>
     * @return The password.
     */
    @Override
    public String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 2;</code>
     * @return The bytes for password.
     */
    @Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 2;</code>
     * @param value The password to set.
     */
    private void setPassword(
        String value) {
      value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 2;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 2;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();
      
    }

    public static LoginRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LoginRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LoginRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LoginRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LoginRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LoginRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.LoginRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LoginRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.LoginRequest)
        LoginRequestOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.LoginSignupProto.LoginRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string username = 1;</code>
       * @return The username.
       */
      @Override
      public String getUsername() {
        return instance.getUsername();
      }
      /**
       * <code>string username = 1;</code>
       * @return The bytes for username.
       */
      @Override
      public com.google.protobuf.ByteString
          getUsernameBytes() {
        return instance.getUsernameBytes();
      }
      /**
       * <code>string username = 1;</code>
       * @param value The username to set.
       * @return This builder for chaining.
       */
      public Builder setUsername(
          String value) {
        copyOnWrite();
        instance.setUsername(value);
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUsername() {
        copyOnWrite();
        instance.clearUsername();
        return this;
      }
      /**
       * <code>string username = 1;</code>
       * @param value The bytes for username to set.
       * @return This builder for chaining.
       */
      public Builder setUsernameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUsernameBytes(value);
        return this;
      }

      /**
       * <code>string password = 2;</code>
       * @return The password.
       */
      @Override
      public String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 2;</code>
       * @return The bytes for password.
       */
      @Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 2;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 2;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.LoginRequest)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LoginRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "username_",
              "password_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0002\u0002\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LoginRequest> parser = PARSER;
          if (parser == null) {
            synchronized (LoginRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LoginRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.LoginRequest)
    private static final LoginRequest DEFAULT_INSTANCE;
    static {
      LoginRequest defaultInstance = new LoginRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LoginRequest.class, defaultInstance);
    }

    public static LoginRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginRequest> PARSER;

    public static com.google.protobuf.Parser<LoginRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LoginResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.LoginResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    String getUserName();
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string emailId = 2;</code>
     * @return The emailId.
     */
    String getEmailId();
    /**
     * <code>string emailId = 2;</code>
     * @return The bytes for emailId.
     */
    com.google.protobuf.ByteString
        getEmailIdBytes();

    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    String getMobileNo();
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    com.google.protobuf.ByteString
        getMobileNoBytes();

    /**
     * <code>int32 picId = 4;</code>
     * @return The picId.
     */
    int getPicId();

    /**
     * <code>int32 userId = 5;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>bytes userImage = 20;</code>
     * @return The userImage.
     */
    com.google.protobuf.ByteString getUserImage();

    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    String getAbout();
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    com.google.protobuf.ByteString
        getAboutBytes();

    /**
     * <code>int32 responseCode = 6;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string responseMessage = 22;</code>
     * @return The responseMessage.
     */
    String getResponseMessage();
    /**
     * <code>string responseMessage = 22;</code>
     * @return The bytes for responseMessage.
     */
    com.google.protobuf.ByteString
        getResponseMessageBytes();
  }
  /**
   * Protobuf type {@code gbuddy.LoginResponse}
   */
  public  static final class LoginResponse extends
      com.google.protobuf.GeneratedMessageLite<
          LoginResponse, LoginResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.LoginResponse)
      LoginResponseOrBuilder {
    private LoginResponse() {
      userName_ = "";
      emailId_ = "";
      mobileNo_ = "";
      userImage_ = com.google.protobuf.ByteString.EMPTY;
      about_ = "";
      responseMessage_ = "";
    }
    public static final int USERNAME_FIELD_NUMBER = 1;
    private String userName_;
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      return userName_;
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     */
    private void setUserName(
        String value) {
      value.getClass();
  
      userName_ = value;
    }
    /**
     * <code>string userName = 1;</code>
     */
    private void clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      userName_ = value.toStringUtf8();
      
    }

    public static final int EMAILID_FIELD_NUMBER = 2;
    private String emailId_;
    /**
     * <code>string emailId = 2;</code>
     * @return The emailId.
     */
    @Override
    public String getEmailId() {
      return emailId_;
    }
    /**
     * <code>string emailId = 2;</code>
     * @return The bytes for emailId.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailId_);
    }
    /**
     * <code>string emailId = 2;</code>
     * @param value The emailId to set.
     */
    private void setEmailId(
        String value) {
      value.getClass();
  
      emailId_ = value;
    }
    /**
     * <code>string emailId = 2;</code>
     */
    private void clearEmailId() {
      
      emailId_ = getDefaultInstance().getEmailId();
    }
    /**
     * <code>string emailId = 2;</code>
     * @param value The bytes for emailId to set.
     */
    private void setEmailIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      emailId_ = value.toStringUtf8();
      
    }

    public static final int MOBILENO_FIELD_NUMBER = 3;
    private String mobileNo_;
    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    @Override
    public String getMobileNo() {
      return mobileNo_;
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    @Override
    public com.google.protobuf.ByteString
        getMobileNoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mobileNo_);
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The mobileNo to set.
     */
    private void setMobileNo(
        String value) {
      value.getClass();
  
      mobileNo_ = value;
    }
    /**
     * <code>string mobileNo = 3;</code>
     */
    private void clearMobileNo() {
      
      mobileNo_ = getDefaultInstance().getMobileNo();
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The bytes for mobileNo to set.
     */
    private void setMobileNoBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      mobileNo_ = value.toStringUtf8();
      
    }

    public static final int PICID_FIELD_NUMBER = 4;
    private int picId_;
    /**
     * <code>int32 picId = 4;</code>
     * @return The picId.
     */
    @Override
    public int getPicId() {
      return picId_;
    }
    /**
     * <code>int32 picId = 4;</code>
     * @param value The picId to set.
     */
    private void setPicId(int value) {
      
      picId_ = value;
    }
    /**
     * <code>int32 picId = 4;</code>
     */
    private void clearPicId() {
      
      picId_ = 0;
    }

    public static final int USERID_FIELD_NUMBER = 5;
    private int userId_;
    /**
     * <code>int32 userId = 5;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 5;</code>
     * @param value The userId to set.
     */
    private void setUserId(int value) {
      
      userId_ = value;
    }
    /**
     * <code>int32 userId = 5;</code>
     */
    private void clearUserId() {
      
      userId_ = 0;
    }

    public static final int USERIMAGE_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString userImage_;
    /**
     * <code>bytes userImage = 20;</code>
     * @return The userImage.
     */
    @Override
    public com.google.protobuf.ByteString getUserImage() {
      return userImage_;
    }
    /**
     * <code>bytes userImage = 20;</code>
     * @param value The userImage to set.
     */
    private void setUserImage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      userImage_ = value;
    }
    /**
     * <code>bytes userImage = 20;</code>
     */
    private void clearUserImage() {
      
      userImage_ = getDefaultInstance().getUserImage();
    }

    public static final int ABOUT_FIELD_NUMBER = 21;
    private String about_;
    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    @Override
    public String getAbout() {
      return about_;
    }
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    @Override
    public com.google.protobuf.ByteString
        getAboutBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(about_);
    }
    /**
     * <code>string about = 21;</code>
     * @param value The about to set.
     */
    private void setAbout(
        String value) {
      value.getClass();
  
      about_ = value;
    }
    /**
     * <code>string about = 21;</code>
     */
    private void clearAbout() {
      
      about_ = getDefaultInstance().getAbout();
    }
    /**
     * <code>string about = 21;</code>
     * @param value The bytes for about to set.
     */
    private void setAboutBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      about_ = value.toStringUtf8();
      
    }

    public static final int RESPONSECODE_FIELD_NUMBER = 6;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 6;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 6;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 6;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int RESPONSEMESSAGE_FIELD_NUMBER = 22;
    private String responseMessage_;
    /**
     * <code>string responseMessage = 22;</code>
     * @return The responseMessage.
     */
    @Override
    public String getResponseMessage() {
      return responseMessage_;
    }
    /**
     * <code>string responseMessage = 22;</code>
     * @return The bytes for responseMessage.
     */
    @Override
    public com.google.protobuf.ByteString
        getResponseMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(responseMessage_);
    }
    /**
     * <code>string responseMessage = 22;</code>
     * @param value The responseMessage to set.
     */
    private void setResponseMessage(
        String value) {
      value.getClass();
  
      responseMessage_ = value;
    }
    /**
     * <code>string responseMessage = 22;</code>
     */
    private void clearResponseMessage() {
      
      responseMessage_ = getDefaultInstance().getResponseMessage();
    }
    /**
     * <code>string responseMessage = 22;</code>
     * @param value The bytes for responseMessage to set.
     */
    private void setResponseMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      responseMessage_ = value.toStringUtf8();
      
    }

    public static LoginResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LoginResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LoginResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LoginResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LoginResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LoginResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LoginResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LoginResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.LoginResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LoginResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.LoginResponse)
        LoginResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.LoginSignupProto.LoginResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string userName = 1;</code>
       * @return The userName.
       */
      @Override
      public String getUserName() {
        return instance.getUserName();
      }
      /**
       * <code>string userName = 1;</code>
       * @return The bytes for userName.
       */
      @Override
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>string emailId = 2;</code>
       * @return The emailId.
       */
      @Override
      public String getEmailId() {
        return instance.getEmailId();
      }
      /**
       * <code>string emailId = 2;</code>
       * @return The bytes for emailId.
       */
      @Override
      public com.google.protobuf.ByteString
          getEmailIdBytes() {
        return instance.getEmailIdBytes();
      }
      /**
       * <code>string emailId = 2;</code>
       * @param value The emailId to set.
       * @return This builder for chaining.
       */
      public Builder setEmailId(
          String value) {
        copyOnWrite();
        instance.setEmailId(value);
        return this;
      }
      /**
       * <code>string emailId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailId() {
        copyOnWrite();
        instance.clearEmailId();
        return this;
      }
      /**
       * <code>string emailId = 2;</code>
       * @param value The bytes for emailId to set.
       * @return This builder for chaining.
       */
      public Builder setEmailIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailIdBytes(value);
        return this;
      }

      /**
       * <code>string mobileNo = 3;</code>
       * @return The mobileNo.
       */
      @Override
      public String getMobileNo() {
        return instance.getMobileNo();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return The bytes for mobileNo.
       */
      @Override
      public com.google.protobuf.ByteString
          getMobileNoBytes() {
        return instance.getMobileNoBytes();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNo(
          String value) {
        copyOnWrite();
        instance.setMobileNo(value);
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileNo() {
        copyOnWrite();
        instance.clearMobileNo();
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The bytes for mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMobileNoBytes(value);
        return this;
      }

      /**
       * <code>int32 picId = 4;</code>
       * @return The picId.
       */
      @Override
      public int getPicId() {
        return instance.getPicId();
      }
      /**
       * <code>int32 picId = 4;</code>
       * @param value The picId to set.
       * @return This builder for chaining.
       */
      public Builder setPicId(int value) {
        copyOnWrite();
        instance.setPicId(value);
        return this;
      }
      /**
       * <code>int32 picId = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPicId() {
        copyOnWrite();
        instance.clearPicId();
        return this;
      }

      /**
       * <code>int32 userId = 5;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>int32 userId = 5;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>int32 userId = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <code>bytes userImage = 20;</code>
       * @return The userImage.
       */
      @Override
      public com.google.protobuf.ByteString getUserImage() {
        return instance.getUserImage();
      }
      /**
       * <code>bytes userImage = 20;</code>
       * @param value The userImage to set.
       * @return This builder for chaining.
       */
      public Builder setUserImage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserImage(value);
        return this;
      }
      /**
       * <code>bytes userImage = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserImage() {
        copyOnWrite();
        instance.clearUserImage();
        return this;
      }

      /**
       * <code>string about = 21;</code>
       * @return The about.
       */
      @Override
      public String getAbout() {
        return instance.getAbout();
      }
      /**
       * <code>string about = 21;</code>
       * @return The bytes for about.
       */
      @Override
      public com.google.protobuf.ByteString
          getAboutBytes() {
        return instance.getAboutBytes();
      }
      /**
       * <code>string about = 21;</code>
       * @param value The about to set.
       * @return This builder for chaining.
       */
      public Builder setAbout(
          String value) {
        copyOnWrite();
        instance.setAbout(value);
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbout() {
        copyOnWrite();
        instance.clearAbout();
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @param value The bytes for about to set.
       * @return This builder for chaining.
       */
      public Builder setAboutBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAboutBytes(value);
        return this;
      }

      /**
       * <code>int32 responseCode = 6;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 6;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string responseMessage = 22;</code>
       * @return The responseMessage.
       */
      @Override
      public String getResponseMessage() {
        return instance.getResponseMessage();
      }
      /**
       * <code>string responseMessage = 22;</code>
       * @return The bytes for responseMessage.
       */
      @Override
      public com.google.protobuf.ByteString
          getResponseMessageBytes() {
        return instance.getResponseMessageBytes();
      }
      /**
       * <code>string responseMessage = 22;</code>
       * @param value The responseMessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMessage(
          String value) {
        copyOnWrite();
        instance.setResponseMessage(value);
        return this;
      }
      /**
       * <code>string responseMessage = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseMessage() {
        copyOnWrite();
        instance.clearResponseMessage();
        return this;
      }
      /**
       * <code>string responseMessage = 22;</code>
       * @param value The bytes for responseMessage to set.
       * @return This builder for chaining.
       */
      public Builder setResponseMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setResponseMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.LoginResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LoginResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "userName_",
              "emailId_",
              "mobileNo_",
              "picId_",
              "userId_",
              "responseCode_",
              "userImage_",
              "about_",
              "responseMessage_",
            };
            String info =
                "\u0000\t\u0000\u0000\u0001\u0016\t\u0000\u0000\u0000\u0001\u0208\u0002\u0208\u0003" +
                "\u0208\u0004\u0004\u0005\u0004\u0006\u0004\u0014\n\u0015\u0208\u0016\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LoginResponse> parser = PARSER;
          if (parser == null) {
            synchronized (LoginResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LoginResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.LoginResponse)
    private static final LoginResponse DEFAULT_INSTANCE;
    static {
      LoginResponse defaultInstance = new LoginResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LoginResponse.class, defaultInstance);
    }

    public static LoginResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LoginResponse> PARSER;

    public static com.google.protobuf.Parser<LoginResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SignupRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.SignupRequest)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    String getUserName();
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string emailId = 2;</code>
     * @return The emailId.
     */
    String getEmailId();
    /**
     * <code>string emailId = 2;</code>
     * @return The bytes for emailId.
     */
    com.google.protobuf.ByteString
        getEmailIdBytes();

    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    String getMobileNo();
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    com.google.protobuf.ByteString
        getMobileNoBytes();

    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    String getPassword();
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    com.google.protobuf.ByteString
        getPasswordBytes();

    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @return The enum numeric value on the wire for roles.
     */
    int getRolesValue();
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @return The roles.
     */
    RoleType getRoles();

    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    String getAbout();
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    com.google.protobuf.ByteString
        getAboutBytes();

    /**
     * <code>bytes userImage = 22;</code>
     * @return The userImage.
     */
    com.google.protobuf.ByteString getUserImage();
  }
  /**
   * Protobuf type {@code gbuddy.SignupRequest}
   */
  public  static final class SignupRequest extends
      com.google.protobuf.GeneratedMessageLite<
          SignupRequest, SignupRequest.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.SignupRequest)
      SignupRequestOrBuilder {
    private SignupRequest() {
      userName_ = "";
      emailId_ = "";
      mobileNo_ = "";
      password_ = "";
      about_ = "";
      userImage_ = com.google.protobuf.ByteString.EMPTY;
    }
    public static final int USERNAME_FIELD_NUMBER = 1;
    private String userName_;
    /**
     * <code>string userName = 1;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      return userName_;
    }
    /**
     * <code>string userName = 1;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The userName to set.
     */
    private void setUserName(
        String value) {
      value.getClass();
  
      userName_ = value;
    }
    /**
     * <code>string userName = 1;</code>
     */
    private void clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <code>string userName = 1;</code>
     * @param value The bytes for userName to set.
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      userName_ = value.toStringUtf8();
      
    }

    public static final int EMAILID_FIELD_NUMBER = 2;
    private String emailId_;
    /**
     * <code>string emailId = 2;</code>
     * @return The emailId.
     */
    @Override
    public String getEmailId() {
      return emailId_;
    }
    /**
     * <code>string emailId = 2;</code>
     * @return The bytes for emailId.
     */
    @Override
    public com.google.protobuf.ByteString
        getEmailIdBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(emailId_);
    }
    /**
     * <code>string emailId = 2;</code>
     * @param value The emailId to set.
     */
    private void setEmailId(
        String value) {
      value.getClass();
  
      emailId_ = value;
    }
    /**
     * <code>string emailId = 2;</code>
     */
    private void clearEmailId() {
      
      emailId_ = getDefaultInstance().getEmailId();
    }
    /**
     * <code>string emailId = 2;</code>
     * @param value The bytes for emailId to set.
     */
    private void setEmailIdBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      emailId_ = value.toStringUtf8();
      
    }

    public static final int MOBILENO_FIELD_NUMBER = 3;
    private String mobileNo_;
    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    @Override
    public String getMobileNo() {
      return mobileNo_;
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    @Override
    public com.google.protobuf.ByteString
        getMobileNoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mobileNo_);
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The mobileNo to set.
     */
    private void setMobileNo(
        String value) {
      value.getClass();
  
      mobileNo_ = value;
    }
    /**
     * <code>string mobileNo = 3;</code>
     */
    private void clearMobileNo() {
      
      mobileNo_ = getDefaultInstance().getMobileNo();
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The bytes for mobileNo to set.
     */
    private void setMobileNoBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      mobileNo_ = value.toStringUtf8();
      
    }

    public static final int PASSWORD_FIELD_NUMBER = 4;
    private String password_;
    /**
     * <code>string password = 4;</code>
     * @return The password.
     */
    @Override
    public String getPassword() {
      return password_;
    }
    /**
     * <code>string password = 4;</code>
     * @return The bytes for password.
     */
    @Override
    public com.google.protobuf.ByteString
        getPasswordBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(password_);
    }
    /**
     * <code>string password = 4;</code>
     * @param value The password to set.
     */
    private void setPassword(
        String value) {
      value.getClass();
  
      password_ = value;
    }
    /**
     * <code>string password = 4;</code>
     */
    private void clearPassword() {
      
      password_ = getDefaultInstance().getPassword();
    }
    /**
     * <code>string password = 4;</code>
     * @param value The bytes for password to set.
     */
    private void setPasswordBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      password_ = value.toStringUtf8();
      
    }

    public static final int ROLES_FIELD_NUMBER = 20;
    private int roles_;
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @return The enum numeric value on the wire for roles.
     */
    @Override
    public int getRolesValue() {
      return roles_;
    }
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @return The roles.
     */
    @Override
    public RoleType getRoles() {
      RoleType result = RoleType.forNumber(roles_);
      return result == null ? RoleType.UNRECOGNIZED : result;
    }
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @param value The enum numeric value on the wire for roles to set.
     */
    private void setRolesValue(int value) {
        roles_ = value;
    }
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     * @param value The roles to set.
     */
    private void setRoles(RoleType value) {
      roles_ = value.getNumber();
      
    }
    /**
     * <code>.gbuddy.RoleType roles = 20;</code>
     */
    private void clearRoles() {
      
      roles_ = 0;
    }

    public static final int ABOUT_FIELD_NUMBER = 21;
    private String about_;
    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    @Override
    public String getAbout() {
      return about_;
    }
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    @Override
    public com.google.protobuf.ByteString
        getAboutBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(about_);
    }
    /**
     * <code>string about = 21;</code>
     * @param value The about to set.
     */
    private void setAbout(
        String value) {
      value.getClass();
  
      about_ = value;
    }
    /**
     * <code>string about = 21;</code>
     */
    private void clearAbout() {
      
      about_ = getDefaultInstance().getAbout();
    }
    /**
     * <code>string about = 21;</code>
     * @param value The bytes for about to set.
     */
    private void setAboutBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      about_ = value.toStringUtf8();
      
    }

    public static final int USERIMAGE_FIELD_NUMBER = 22;
    private com.google.protobuf.ByteString userImage_;
    /**
     * <code>bytes userImage = 22;</code>
     * @return The userImage.
     */
    @Override
    public com.google.protobuf.ByteString getUserImage() {
      return userImage_;
    }
    /**
     * <code>bytes userImage = 22;</code>
     * @param value The userImage to set.
     */
    private void setUserImage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      userImage_ = value;
    }
    /**
     * <code>bytes userImage = 22;</code>
     */
    private void clearUserImage() {
      
      userImage_ = getDefaultInstance().getUserImage();
    }

    public static SignupRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SignupRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SignupRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static SignupRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SignupRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SignupRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(SignupRequest prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.SignupRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          SignupRequest, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.SignupRequest)
        SignupRequestOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.LoginSignupProto.SignupRequest.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>string userName = 1;</code>
       * @return The userName.
       */
      @Override
      public String getUserName() {
        return instance.getUserName();
      }
      /**
       * <code>string userName = 1;</code>
       * @return The bytes for userName.
       */
      @Override
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <code>string userName = 1;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>string emailId = 2;</code>
       * @return The emailId.
       */
      @Override
      public String getEmailId() {
        return instance.getEmailId();
      }
      /**
       * <code>string emailId = 2;</code>
       * @return The bytes for emailId.
       */
      @Override
      public com.google.protobuf.ByteString
          getEmailIdBytes() {
        return instance.getEmailIdBytes();
      }
      /**
       * <code>string emailId = 2;</code>
       * @param value The emailId to set.
       * @return This builder for chaining.
       */
      public Builder setEmailId(
          String value) {
        copyOnWrite();
        instance.setEmailId(value);
        return this;
      }
      /**
       * <code>string emailId = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearEmailId() {
        copyOnWrite();
        instance.clearEmailId();
        return this;
      }
      /**
       * <code>string emailId = 2;</code>
       * @param value The bytes for emailId to set.
       * @return This builder for chaining.
       */
      public Builder setEmailIdBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setEmailIdBytes(value);
        return this;
      }

      /**
       * <code>string mobileNo = 3;</code>
       * @return The mobileNo.
       */
      @Override
      public String getMobileNo() {
        return instance.getMobileNo();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return The bytes for mobileNo.
       */
      @Override
      public com.google.protobuf.ByteString
          getMobileNoBytes() {
        return instance.getMobileNoBytes();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNo(
          String value) {
        copyOnWrite();
        instance.setMobileNo(value);
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileNo() {
        copyOnWrite();
        instance.clearMobileNo();
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The bytes for mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMobileNoBytes(value);
        return this;
      }

      /**
       * <code>string password = 4;</code>
       * @return The password.
       */
      @Override
      public String getPassword() {
        return instance.getPassword();
      }
      /**
       * <code>string password = 4;</code>
       * @return The bytes for password.
       */
      @Override
      public com.google.protobuf.ByteString
          getPasswordBytes() {
        return instance.getPasswordBytes();
      }
      /**
       * <code>string password = 4;</code>
       * @param value The password to set.
       * @return This builder for chaining.
       */
      public Builder setPassword(
          String value) {
        copyOnWrite();
        instance.setPassword(value);
        return this;
      }
      /**
       * <code>string password = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearPassword() {
        copyOnWrite();
        instance.clearPassword();
        return this;
      }
      /**
       * <code>string password = 4;</code>
       * @param value The bytes for password to set.
       * @return This builder for chaining.
       */
      public Builder setPasswordBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setPasswordBytes(value);
        return this;
      }

      /**
       * <code>.gbuddy.RoleType roles = 20;</code>
       * @return The enum numeric value on the wire for roles.
       */
      @Override
      public int getRolesValue() {
        return instance.getRolesValue();
      }
      /**
       * <code>.gbuddy.RoleType roles = 20;</code>
       * @param value The roles to set.
       * @return This builder for chaining.
       */
      public Builder setRolesValue(int value) {
        copyOnWrite();
        instance.setRolesValue(value);
        return this;
      }
      /**
       * <code>.gbuddy.RoleType roles = 20;</code>
       * @return The roles.
       */
      @Override
      public RoleType getRoles() {
        return instance.getRoles();
      }
      /**
       * <code>.gbuddy.RoleType roles = 20;</code>
       * @param value The enum numeric value on the wire for roles to set.
       * @return This builder for chaining.
       */
      public Builder setRoles(RoleType value) {
        copyOnWrite();
        instance.setRoles(value);
        return this;
      }
      /**
       * <code>.gbuddy.RoleType roles = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearRoles() {
        copyOnWrite();
        instance.clearRoles();
        return this;
      }

      /**
       * <code>string about = 21;</code>
       * @return The about.
       */
      @Override
      public String getAbout() {
        return instance.getAbout();
      }
      /**
       * <code>string about = 21;</code>
       * @return The bytes for about.
       */
      @Override
      public com.google.protobuf.ByteString
          getAboutBytes() {
        return instance.getAboutBytes();
      }
      /**
       * <code>string about = 21;</code>
       * @param value The about to set.
       * @return This builder for chaining.
       */
      public Builder setAbout(
          String value) {
        copyOnWrite();
        instance.setAbout(value);
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbout() {
        copyOnWrite();
        instance.clearAbout();
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @param value The bytes for about to set.
       * @return This builder for chaining.
       */
      public Builder setAboutBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAboutBytes(value);
        return this;
      }

      /**
       * <code>bytes userImage = 22;</code>
       * @return The userImage.
       */
      @Override
      public com.google.protobuf.ByteString getUserImage() {
        return instance.getUserImage();
      }
      /**
       * <code>bytes userImage = 22;</code>
       * @param value The userImage to set.
       * @return This builder for chaining.
       */
      public Builder setUserImage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserImage(value);
        return this;
      }
      /**
       * <code>bytes userImage = 22;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserImage() {
        copyOnWrite();
        instance.clearUserImage();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.SignupRequest)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new SignupRequest();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "userName_",
              "emailId_",
              "mobileNo_",
              "password_",
              "roles_",
              "about_",
              "userImage_",
            };
            String info =
                "\u0000\u0007\u0000\u0000\u0001\u0016\u0007\u0000\u0000\u0000\u0001\u0208\u0002\u0208" +
                "\u0003\u0208\u0004\u0208\u0014\f\u0015\u0208\u0016\n";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<SignupRequest> parser = PARSER;
          if (parser == null) {
            synchronized (SignupRequest.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<SignupRequest>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.SignupRequest)
    private static final SignupRequest DEFAULT_INSTANCE;
    static {
      SignupRequest defaultInstance = new SignupRequest();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SignupRequest.class, defaultInstance);
    }

    public static SignupRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SignupRequest> PARSER;

    public static com.google.protobuf.Parser<SignupRequest> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface SignupResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.SignupResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     * @return Whether the response field is set.
     */
    boolean hasResponse();
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     * @return The response.
     */
    LoginResponse getResponse();
  }
  /**
   * Protobuf type {@code gbuddy.SignupResponse}
   */
  public  static final class SignupResponse extends
      com.google.protobuf.GeneratedMessageLite<
          SignupResponse, SignupResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.SignupResponse)
      SignupResponseOrBuilder {
    private SignupResponse() {
    }
    public static final int RESPONSE_FIELD_NUMBER = 1;
    private LoginResponse response_;
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     */
    @Override
    public boolean hasResponse() {
      return response_ != null;
    }
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     */
    @Override
    public LoginResponse getResponse() {
      return response_ == null ? LoginResponse.getDefaultInstance() : response_;
    }
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     */
    private void setResponse(LoginResponse value) {
      value.getClass();
  response_ = value;
      
      }
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeResponse(LoginResponse value) {
      value.getClass();
  if (response_ != null &&
          response_ != LoginResponse.getDefaultInstance()) {
        response_ =
          LoginResponse.newBuilder(response_).mergeFrom(value).buildPartial();
      } else {
        response_ = value;
      }
      
    }
    /**
     * <code>.gbuddy.LoginResponse response = 1;</code>
     */
    private void clearResponse() {  response_ = null;
      
    }

    public static SignupResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static SignupResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static SignupResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SignupResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SignupResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static SignupResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static SignupResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static SignupResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(SignupResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.SignupResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          SignupResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.SignupResponse)
        SignupResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.LoginSignupProto.SignupResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      @Override
      public boolean hasResponse() {
        return instance.hasResponse();
      }
      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      @Override
      public LoginResponse getResponse() {
        return instance.getResponse();
      }
      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      public Builder setResponse(LoginResponse value) {
        copyOnWrite();
        instance.setResponse(value);
        return this;
        }
      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      public Builder setResponse(
          LoginResponse.Builder builderForValue) {
        copyOnWrite();
        instance.setResponse(builderForValue.build());
        return this;
      }
      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      public Builder mergeResponse(LoginResponse value) {
        copyOnWrite();
        instance.mergeResponse(value);
        return this;
      }
      /**
       * <code>.gbuddy.LoginResponse response = 1;</code>
       */
      public Builder clearResponse() {  copyOnWrite();
        instance.clearResponse();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.SignupResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new SignupResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "response_",
            };
            String info =
                "\u0000\u0001\u0000\u0000\u0001\u0001\u0001\u0000\u0000\u0000\u0001\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<SignupResponse> parser = PARSER;
          if (parser == null) {
            synchronized (SignupResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<SignupResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.SignupResponse)
    private static final SignupResponse DEFAULT_INSTANCE;
    static {
      SignupResponse defaultInstance = new SignupResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        SignupResponse.class, defaultInstance);
    }

    public static SignupResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<SignupResponse> PARSER;

    public static com.google.protobuf.Parser<SignupResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
