// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: matchlookup.proto

package com.example.gym.buddies.data.protos;

public final class MatchLookupProto {
  private MatchLookupProto() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }
  /**
   * Protobuf enum {@code gbuddy.Status}
   */
  public enum Status
      implements com.google.protobuf.Internal.EnumLite {
    /**
     * <code>MATCHED = 0;</code>
     */
    MATCHED(0),
    /**
     * <code>UNMATCHED = 1;</code>
     */
    UNMATCHED(1),
    /**
     * <code>REQUESTED = 2;</code>
     */
    REQUESTED(2),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>MATCHED = 0;</code>
     */
    public static final int MATCHED_VALUE = 0;
    /**
     * <code>UNMATCHED = 1;</code>
     */
    public static final int UNMATCHED_VALUE = 1;
    /**
     * <code>REQUESTED = 2;</code>
     */
    public static final int REQUESTED_VALUE = 2;


    @Override
    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The number of the enum to look for.
     * @return The enum associated with the given number.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @Deprecated
    public static Status valueOf(int value) {
      return forNumber(value);
    }

    public static Status forNumber(int value) {
      switch (value) {
        case 0: return MATCHED;
        case 1: return UNMATCHED;
        case 2: return REQUESTED;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Status>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Status> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Status>() {
            @Override
            public Status findValueByNumber(int number) {
              return Status.forNumber(number);
            }
          };

    public static com.google.protobuf.Internal.EnumVerifier 
        internalGetVerifier() {
      return StatusVerifier.INSTANCE;
    }

    private static final class StatusVerifier implements 
         com.google.protobuf.Internal.EnumVerifier { 
            static final com.google.protobuf.Internal.EnumVerifier           INSTANCE = new StatusVerifier();
            @Override
            public boolean isInRange(int number) {
              return Status.forNumber(number) != null;
            }
          };

    private final int value;

    private Status(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:gbuddy.Status)
  }

  public interface MatchResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.MatchResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * Protobuf type {@code gbuddy.MatchResponse}
   */
  public  static final class MatchResponse extends
      com.google.protobuf.GeneratedMessageLite<
          MatchResponse, MatchResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.MatchResponse)
      MatchResponseOrBuilder {
    private MatchResponse() {
      message_ = "";
    }
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 16;
    private String message_;
    /**
     * <code>string message = 16;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 16;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 16;</code>
     * @param value The message to set.
     */
    private void setMessage(
        String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 16;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 16;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static MatchResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MatchResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MatchResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static MatchResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MatchResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(MatchResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.MatchResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          MatchResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.MatchResponse)
        MatchResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.MatchResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 responseCode = 1;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string message = 16;</code>
       * @return The message.
       */
      @Override
      public String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 16;</code>
       * @return The bytes for message.
       */
      @Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 16;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 16;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.MatchResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new MatchResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "responseCode_",
              "message_",
            };
            String info =
                "\u0000\u0002\u0000\u0000\u0001\u0010\u0002\u0000\u0000\u0000\u0001\u0004\u0010\u0208" +
                "";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<MatchResponse> parser = PARSER;
          if (parser == null) {
            synchronized (MatchResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<MatchResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.MatchResponse)
    private static final MatchResponse DEFAULT_INSTANCE;
    static {
      MatchResponse defaultInstance = new MatchResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MatchResponse.class, defaultInstance);
    }

    public static MatchResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MatchResponse> PARSER;

    public static com.google.protobuf.Parser<MatchResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface MatchLookupOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.MatchLookup)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    int getId();

    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    int getStatusValue();
    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @return The status.
     */
    Status getStatus();

    /**
     * <code>.gbuddy.User user = 16;</code>
     * @return Whether the user field is set.
     */
    boolean hasUser();
    /**
     * <code>.gbuddy.User user = 16;</code>
     * @return The user.
     */
    User getUser();

    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     * @return Whether the gym field is set.
     */
    boolean hasGym();
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     * @return The gym.
     */
    Gym getGym();
  }
  /**
   * Protobuf type {@code gbuddy.MatchLookup}
   */
  public  static final class MatchLookup extends
      com.google.protobuf.GeneratedMessageLite<
          MatchLookup, MatchLookup.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.MatchLookup)
      MatchLookupOrBuilder {
    private MatchLookup() {
    }
    public static final int ID_FIELD_NUMBER = 1;
    private int id_;
    /**
     * <code>int32 id = 1;</code>
     * @return The id.
     */
    @Override
    public int getId() {
      return id_;
    }
    /**
     * <code>int32 id = 1;</code>
     * @param value The id to set.
     */
    private void setId(int value) {
      
      id_ = value;
    }
    /**
     * <code>int32 id = 1;</code>
     */
    private void clearId() {
      
      id_ = 0;
    }

    public static final int STATUS_FIELD_NUMBER = 5;
    private int status_;
    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @return The enum numeric value on the wire for status.
     */
    @Override
    public int getStatusValue() {
      return status_;
    }
    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @return The status.
     */
    @Override
    public Status getStatus() {
      Status result = Status.forNumber(status_);
      return result == null ? Status.UNRECOGNIZED : result;
    }
    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @param value The enum numeric value on the wire for status to set.
     */
    private void setStatusValue(int value) {
        status_ = value;
    }
    /**
     * <code>.gbuddy.Status status = 5;</code>
     * @param value The status to set.
     */
    private void setStatus(Status value) {
      status_ = value.getNumber();
      
    }
    /**
     * <code>.gbuddy.Status status = 5;</code>
     */
    private void clearStatus() {
      
      status_ = 0;
    }

    public static final int USER_FIELD_NUMBER = 16;
    private User user_;
    /**
     * <code>.gbuddy.User user = 16;</code>
     */
    @Override
    public boolean hasUser() {
      return user_ != null;
    }
    /**
     * <code>.gbuddy.User user = 16;</code>
     */
    @Override
    public User getUser() {
      return user_ == null ? User.getDefaultInstance() : user_;
    }
    /**
     * <code>.gbuddy.User user = 16;</code>
     */
    private void setUser(User value) {
      value.getClass();
  user_ = value;
      
      }
    /**
     * <code>.gbuddy.User user = 16;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeUser(User value) {
      value.getClass();
  if (user_ != null &&
          user_ != User.getDefaultInstance()) {
        user_ =
          User.newBuilder(user_).mergeFrom(value).buildPartial();
      } else {
        user_ = value;
      }
      
    }
    /**
     * <code>.gbuddy.User user = 16;</code>
     */
    private void clearUser() {  user_ = null;
      
    }

    public static final int GYM_FIELD_NUMBER = 17;
    private Gym gym_;
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     */
    @Override
    public boolean hasGym() {
      return gym_ != null;
    }
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     */
    @Override
    public Gym getGym() {
      return gym_ == null ? Gym.getDefaultInstance() : gym_;
    }
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     */
    private void setGym(Gym value) {
      value.getClass();
  gym_ = value;
      
      }
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeGym(Gym value) {
      value.getClass();
  if (gym_ != null &&
          gym_ != Gym.getDefaultInstance()) {
        gym_ =
          Gym.newBuilder(gym_).mergeFrom(value).buildPartial();
      } else {
        gym_ = value;
      }
      
    }
    /**
     * <code>.gbuddy.Gym gym = 17;</code>
     */
    private void clearGym() {  gym_ = null;
      
    }

    public static MatchLookup parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchLookup parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchLookup parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchLookup parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchLookup parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static MatchLookup parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static MatchLookup parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MatchLookup parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MatchLookup parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static MatchLookup parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static MatchLookup parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static MatchLookup parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(MatchLookup prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.MatchLookup}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          MatchLookup, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.MatchLookup)
        MatchLookupOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.MatchLookup.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 id = 1;</code>
       * @return The id.
       */
      @Override
      public int getId() {
        return instance.getId();
      }
      /**
       * <code>int32 id = 1;</code>
       * @param value The id to set.
       * @return This builder for chaining.
       */
      public Builder setId(int value) {
        copyOnWrite();
        instance.setId(value);
        return this;
      }
      /**
       * <code>int32 id = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearId() {
        copyOnWrite();
        instance.clearId();
        return this;
      }

      /**
       * <code>.gbuddy.Status status = 5;</code>
       * @return The enum numeric value on the wire for status.
       */
      @Override
      public int getStatusValue() {
        return instance.getStatusValue();
      }
      /**
       * <code>.gbuddy.Status status = 5;</code>
       * @param value The status to set.
       * @return This builder for chaining.
       */
      public Builder setStatusValue(int value) {
        copyOnWrite();
        instance.setStatusValue(value);
        return this;
      }
      /**
       * <code>.gbuddy.Status status = 5;</code>
       * @return The status.
       */
      @Override
      public Status getStatus() {
        return instance.getStatus();
      }
      /**
       * <code>.gbuddy.Status status = 5;</code>
       * @param value The enum numeric value on the wire for status to set.
       * @return This builder for chaining.
       */
      public Builder setStatus(Status value) {
        copyOnWrite();
        instance.setStatus(value);
        return this;
      }
      /**
       * <code>.gbuddy.Status status = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearStatus() {
        copyOnWrite();
        instance.clearStatus();
        return this;
      }

      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      @Override
      public boolean hasUser() {
        return instance.hasUser();
      }
      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      @Override
      public User getUser() {
        return instance.getUser();
      }
      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      public Builder setUser(User value) {
        copyOnWrite();
        instance.setUser(value);
        return this;
        }
      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      public Builder setUser(
          User.Builder builderForValue) {
        copyOnWrite();
        instance.setUser(builderForValue.build());
        return this;
      }
      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      public Builder mergeUser(User value) {
        copyOnWrite();
        instance.mergeUser(value);
        return this;
      }
      /**
       * <code>.gbuddy.User user = 16;</code>
       */
      public Builder clearUser() {  copyOnWrite();
        instance.clearUser();
        return this;
      }

      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      @Override
      public boolean hasGym() {
        return instance.hasGym();
      }
      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      @Override
      public Gym getGym() {
        return instance.getGym();
      }
      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      public Builder setGym(Gym value) {
        copyOnWrite();
        instance.setGym(value);
        return this;
        }
      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      public Builder setGym(
          Gym.Builder builderForValue) {
        copyOnWrite();
        instance.setGym(builderForValue.build());
        return this;
      }
      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      public Builder mergeGym(Gym value) {
        copyOnWrite();
        instance.mergeGym(value);
        return this;
      }
      /**
       * <code>.gbuddy.Gym gym = 17;</code>
       */
      public Builder clearGym() {  copyOnWrite();
        instance.clearGym();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.MatchLookup)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new MatchLookup();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "id_",
              "status_",
              "user_",
              "gym_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0011\u0004\u0000\u0000\u0000\u0001\u0004\u0005\f" +
                "\u0010\t\u0011\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<MatchLookup> parser = PARSER;
          if (parser == null) {
            synchronized (MatchLookup.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<MatchLookup>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.MatchLookup)
    private static final MatchLookup DEFAULT_INSTANCE;
    static {
      MatchLookup defaultInstance = new MatchLookup();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        MatchLookup.class, defaultInstance);
    }

    public static MatchLookup getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<MatchLookup> PARSER;

    public static com.google.protobuf.Parser<MatchLookup> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface UserOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.User)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    int getUserId();

    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    String getUserName();
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    com.google.protobuf.ByteString
        getUserNameBytes();

    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    String getMobileNo();
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    com.google.protobuf.ByteString
        getMobileNoBytes();

    /**
     * <code>bytes userImage = 20;</code>
     * @return The userImage.
     */
    com.google.protobuf.ByteString getUserImage();

    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    String getAbout();
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    com.google.protobuf.ByteString
        getAboutBytes();
  }
  /**
   * Protobuf type {@code gbuddy.User}
   */
  public  static final class User extends
      com.google.protobuf.GeneratedMessageLite<
          User, User.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.User)
      UserOrBuilder {
    private User() {
      userName_ = "";
      mobileNo_ = "";
      userImage_ = com.google.protobuf.ByteString.EMPTY;
      about_ = "";
    }
    public static final int USERID_FIELD_NUMBER = 1;
    private int userId_;
    /**
     * <code>int32 userId = 1;</code>
     * @return The userId.
     */
    @Override
    public int getUserId() {
      return userId_;
    }
    /**
     * <code>int32 userId = 1;</code>
     * @param value The userId to set.
     */
    private void setUserId(int value) {
      
      userId_ = value;
    }
    /**
     * <code>int32 userId = 1;</code>
     */
    private void clearUserId() {
      
      userId_ = 0;
    }

    public static final int USERNAME_FIELD_NUMBER = 2;
    private String userName_;
    /**
     * <code>string userName = 2;</code>
     * @return The userName.
     */
    @Override
    public String getUserName() {
      return userName_;
    }
    /**
     * <code>string userName = 2;</code>
     * @return The bytes for userName.
     */
    @Override
    public com.google.protobuf.ByteString
        getUserNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(userName_);
    }
    /**
     * <code>string userName = 2;</code>
     * @param value The userName to set.
     */
    private void setUserName(
        String value) {
      value.getClass();
  
      userName_ = value;
    }
    /**
     * <code>string userName = 2;</code>
     */
    private void clearUserName() {
      
      userName_ = getDefaultInstance().getUserName();
    }
    /**
     * <code>string userName = 2;</code>
     * @param value The bytes for userName to set.
     */
    private void setUserNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      userName_ = value.toStringUtf8();
      
    }

    public static final int MOBILENO_FIELD_NUMBER = 3;
    private String mobileNo_;
    /**
     * <code>string mobileNo = 3;</code>
     * @return The mobileNo.
     */
    @Override
    public String getMobileNo() {
      return mobileNo_;
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @return The bytes for mobileNo.
     */
    @Override
    public com.google.protobuf.ByteString
        getMobileNoBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(mobileNo_);
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The mobileNo to set.
     */
    private void setMobileNo(
        String value) {
      value.getClass();
  
      mobileNo_ = value;
    }
    /**
     * <code>string mobileNo = 3;</code>
     */
    private void clearMobileNo() {
      
      mobileNo_ = getDefaultInstance().getMobileNo();
    }
    /**
     * <code>string mobileNo = 3;</code>
     * @param value The bytes for mobileNo to set.
     */
    private void setMobileNoBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      mobileNo_ = value.toStringUtf8();
      
    }

    public static final int USERIMAGE_FIELD_NUMBER = 20;
    private com.google.protobuf.ByteString userImage_;
    /**
     * <code>bytes userImage = 20;</code>
     * @return The userImage.
     */
    @Override
    public com.google.protobuf.ByteString getUserImage() {
      return userImage_;
    }
    /**
     * <code>bytes userImage = 20;</code>
     * @param value The userImage to set.
     */
    private void setUserImage(com.google.protobuf.ByteString value) {
      value.getClass();
  
      userImage_ = value;
    }
    /**
     * <code>bytes userImage = 20;</code>
     */
    private void clearUserImage() {
      
      userImage_ = getDefaultInstance().getUserImage();
    }

    public static final int ABOUT_FIELD_NUMBER = 21;
    private String about_;
    /**
     * <code>string about = 21;</code>
     * @return The about.
     */
    @Override
    public String getAbout() {
      return about_;
    }
    /**
     * <code>string about = 21;</code>
     * @return The bytes for about.
     */
    @Override
    public com.google.protobuf.ByteString
        getAboutBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(about_);
    }
    /**
     * <code>string about = 21;</code>
     * @param value The about to set.
     */
    private void setAbout(
        String value) {
      value.getClass();
  
      about_ = value;
    }
    /**
     * <code>string about = 21;</code>
     */
    private void clearAbout() {
      
      about_ = getDefaultInstance().getAbout();
    }
    /**
     * <code>string about = 21;</code>
     * @param value The bytes for about to set.
     */
    private void setAboutBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      about_ = value.toStringUtf8();
      
    }

    public static User parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static User parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static User parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static User parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static User parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(User prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.User}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          User, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.User)
        UserOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.User.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 userId = 1;</code>
       * @return The userId.
       */
      @Override
      public int getUserId() {
        return instance.getUserId();
      }
      /**
       * <code>int32 userId = 1;</code>
       * @param value The userId to set.
       * @return This builder for chaining.
       */
      public Builder setUserId(int value) {
        copyOnWrite();
        instance.setUserId(value);
        return this;
      }
      /**
       * <code>int32 userId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserId() {
        copyOnWrite();
        instance.clearUserId();
        return this;
      }

      /**
       * <code>string userName = 2;</code>
       * @return The userName.
       */
      @Override
      public String getUserName() {
        return instance.getUserName();
      }
      /**
       * <code>string userName = 2;</code>
       * @return The bytes for userName.
       */
      @Override
      public com.google.protobuf.ByteString
          getUserNameBytes() {
        return instance.getUserNameBytes();
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserName(
          String value) {
        copyOnWrite();
        instance.setUserName(value);
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserName() {
        copyOnWrite();
        instance.clearUserName();
        return this;
      }
      /**
       * <code>string userName = 2;</code>
       * @param value The bytes for userName to set.
       * @return This builder for chaining.
       */
      public Builder setUserNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserNameBytes(value);
        return this;
      }

      /**
       * <code>string mobileNo = 3;</code>
       * @return The mobileNo.
       */
      @Override
      public String getMobileNo() {
        return instance.getMobileNo();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return The bytes for mobileNo.
       */
      @Override
      public com.google.protobuf.ByteString
          getMobileNoBytes() {
        return instance.getMobileNoBytes();
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNo(
          String value) {
        copyOnWrite();
        instance.setMobileNo(value);
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMobileNo() {
        copyOnWrite();
        instance.clearMobileNo();
        return this;
      }
      /**
       * <code>string mobileNo = 3;</code>
       * @param value The bytes for mobileNo to set.
       * @return This builder for chaining.
       */
      public Builder setMobileNoBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMobileNoBytes(value);
        return this;
      }

      /**
       * <code>bytes userImage = 20;</code>
       * @return The userImage.
       */
      @Override
      public com.google.protobuf.ByteString getUserImage() {
        return instance.getUserImage();
      }
      /**
       * <code>bytes userImage = 20;</code>
       * @param value The userImage to set.
       * @return This builder for chaining.
       */
      public Builder setUserImage(com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setUserImage(value);
        return this;
      }
      /**
       * <code>bytes userImage = 20;</code>
       * @return This builder for chaining.
       */
      public Builder clearUserImage() {
        copyOnWrite();
        instance.clearUserImage();
        return this;
      }

      /**
       * <code>string about = 21;</code>
       * @return The about.
       */
      @Override
      public String getAbout() {
        return instance.getAbout();
      }
      /**
       * <code>string about = 21;</code>
       * @return The bytes for about.
       */
      @Override
      public com.google.protobuf.ByteString
          getAboutBytes() {
        return instance.getAboutBytes();
      }
      /**
       * <code>string about = 21;</code>
       * @param value The about to set.
       * @return This builder for chaining.
       */
      public Builder setAbout(
          String value) {
        copyOnWrite();
        instance.setAbout(value);
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @return This builder for chaining.
       */
      public Builder clearAbout() {
        copyOnWrite();
        instance.clearAbout();
        return this;
      }
      /**
       * <code>string about = 21;</code>
       * @param value The bytes for about to set.
       * @return This builder for chaining.
       */
      public Builder setAboutBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setAboutBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.User)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new User();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "userId_",
              "userName_",
              "mobileNo_",
              "userImage_",
              "about_",
            };
            String info =
                "\u0000\u0005\u0000\u0000\u0001\u0015\u0005\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0014\n\u0015\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<User> parser = PARSER;
          if (parser == null) {
            synchronized (User.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<User>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.User)
    private static final User DEFAULT_INSTANCE;
    static {
      User defaultInstance = new User();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        User.class, defaultInstance);
    }

    public static User getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<User> PARSER;

    public static com.google.protobuf.Parser<User> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface GymOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.Gym)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 gymId = 1;</code>
     * @return The gymId.
     */
    int getGymId();

    /**
     * <code>string gymName = 2;</code>
     * @return The gymName.
     */
    String getGymName();
    /**
     * <code>string gymName = 2;</code>
     * @return The bytes for gymName.
     */
    com.google.protobuf.ByteString
        getGymNameBytes();

    /**
     * <code>string website = 3;</code>
     * @return The website.
     */
    String getWebsite();
    /**
     * <code>string website = 3;</code>
     * @return The bytes for website.
     */
    com.google.protobuf.ByteString
        getWebsiteBytes();

    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     * @return Whether the branch field is set.
     */
    boolean hasBranch();
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     * @return The branch.
     */
    Branch getBranch();
  }
  /**
   * Protobuf type {@code gbuddy.Gym}
   */
  public  static final class Gym extends
      com.google.protobuf.GeneratedMessageLite<
          Gym, Gym.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.Gym)
      GymOrBuilder {
    private Gym() {
      gymName_ = "";
      website_ = "";
    }
    public static final int GYMID_FIELD_NUMBER = 1;
    private int gymId_;
    /**
     * <code>int32 gymId = 1;</code>
     * @return The gymId.
     */
    @Override
    public int getGymId() {
      return gymId_;
    }
    /**
     * <code>int32 gymId = 1;</code>
     * @param value The gymId to set.
     */
    private void setGymId(int value) {
      
      gymId_ = value;
    }
    /**
     * <code>int32 gymId = 1;</code>
     */
    private void clearGymId() {
      
      gymId_ = 0;
    }

    public static final int GYMNAME_FIELD_NUMBER = 2;
    private String gymName_;
    /**
     * <code>string gymName = 2;</code>
     * @return The gymName.
     */
    @Override
    public String getGymName() {
      return gymName_;
    }
    /**
     * <code>string gymName = 2;</code>
     * @return The bytes for gymName.
     */
    @Override
    public com.google.protobuf.ByteString
        getGymNameBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(gymName_);
    }
    /**
     * <code>string gymName = 2;</code>
     * @param value The gymName to set.
     */
    private void setGymName(
        String value) {
      value.getClass();
  
      gymName_ = value;
    }
    /**
     * <code>string gymName = 2;</code>
     */
    private void clearGymName() {
      
      gymName_ = getDefaultInstance().getGymName();
    }
    /**
     * <code>string gymName = 2;</code>
     * @param value The bytes for gymName to set.
     */
    private void setGymNameBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      gymName_ = value.toStringUtf8();
      
    }

    public static final int WEBSITE_FIELD_NUMBER = 3;
    private String website_;
    /**
     * <code>string website = 3;</code>
     * @return The website.
     */
    @Override
    public String getWebsite() {
      return website_;
    }
    /**
     * <code>string website = 3;</code>
     * @return The bytes for website.
     */
    @Override
    public com.google.protobuf.ByteString
        getWebsiteBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(website_);
    }
    /**
     * <code>string website = 3;</code>
     * @param value The website to set.
     */
    private void setWebsite(
        String value) {
      value.getClass();
  
      website_ = value;
    }
    /**
     * <code>string website = 3;</code>
     */
    private void clearWebsite() {
      
      website_ = getDefaultInstance().getWebsite();
    }
    /**
     * <code>string website = 3;</code>
     * @param value The bytes for website to set.
     */
    private void setWebsiteBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      website_ = value.toStringUtf8();
      
    }

    public static final int BRANCH_FIELD_NUMBER = 16;
    private Branch branch_;
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     */
    @Override
    public boolean hasBranch() {
      return branch_ != null;
    }
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     */
    @Override
    public Branch getBranch() {
      return branch_ == null ? Branch.getDefaultInstance() : branch_;
    }
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     */
    private void setBranch(Branch value) {
      value.getClass();
  branch_ = value;
      
      }
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     */
    @SuppressWarnings({"ReferenceEquality"})
    private void mergeBranch(Branch value) {
      value.getClass();
  if (branch_ != null &&
          branch_ != Branch.getDefaultInstance()) {
        branch_ =
          Branch.newBuilder(branch_).mergeFrom(value).buildPartial();
      } else {
        branch_ = value;
      }
      
    }
    /**
     * <code>.gbuddy.Branch branch = 16;</code>
     */
    private void clearBranch() {  branch_ = null;
      
    }

    public static Gym parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Gym parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Gym parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Gym parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Gym parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Gym parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Gym parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Gym parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Gym prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.Gym}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Gym, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.Gym)
        GymOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.Gym.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 gymId = 1;</code>
       * @return The gymId.
       */
      @Override
      public int getGymId() {
        return instance.getGymId();
      }
      /**
       * <code>int32 gymId = 1;</code>
       * @param value The gymId to set.
       * @return This builder for chaining.
       */
      public Builder setGymId(int value) {
        copyOnWrite();
        instance.setGymId(value);
        return this;
      }
      /**
       * <code>int32 gymId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearGymId() {
        copyOnWrite();
        instance.clearGymId();
        return this;
      }

      /**
       * <code>string gymName = 2;</code>
       * @return The gymName.
       */
      @Override
      public String getGymName() {
        return instance.getGymName();
      }
      /**
       * <code>string gymName = 2;</code>
       * @return The bytes for gymName.
       */
      @Override
      public com.google.protobuf.ByteString
          getGymNameBytes() {
        return instance.getGymNameBytes();
      }
      /**
       * <code>string gymName = 2;</code>
       * @param value The gymName to set.
       * @return This builder for chaining.
       */
      public Builder setGymName(
          String value) {
        copyOnWrite();
        instance.setGymName(value);
        return this;
      }
      /**
       * <code>string gymName = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearGymName() {
        copyOnWrite();
        instance.clearGymName();
        return this;
      }
      /**
       * <code>string gymName = 2;</code>
       * @param value The bytes for gymName to set.
       * @return This builder for chaining.
       */
      public Builder setGymNameBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setGymNameBytes(value);
        return this;
      }

      /**
       * <code>string website = 3;</code>
       * @return The website.
       */
      @Override
      public String getWebsite() {
        return instance.getWebsite();
      }
      /**
       * <code>string website = 3;</code>
       * @return The bytes for website.
       */
      @Override
      public com.google.protobuf.ByteString
          getWebsiteBytes() {
        return instance.getWebsiteBytes();
      }
      /**
       * <code>string website = 3;</code>
       * @param value The website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsite(
          String value) {
        copyOnWrite();
        instance.setWebsite(value);
        return this;
      }
      /**
       * <code>string website = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearWebsite() {
        copyOnWrite();
        instance.clearWebsite();
        return this;
      }
      /**
       * <code>string website = 3;</code>
       * @param value The bytes for website to set.
       * @return This builder for chaining.
       */
      public Builder setWebsiteBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setWebsiteBytes(value);
        return this;
      }

      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      @Override
      public boolean hasBranch() {
        return instance.hasBranch();
      }
      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      @Override
      public Branch getBranch() {
        return instance.getBranch();
      }
      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      public Builder setBranch(Branch value) {
        copyOnWrite();
        instance.setBranch(value);
        return this;
        }
      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      public Builder setBranch(
          Branch.Builder builderForValue) {
        copyOnWrite();
        instance.setBranch(builderForValue.build());
        return this;
      }
      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      public Builder mergeBranch(Branch value) {
        copyOnWrite();
        instance.mergeBranch(value);
        return this;
      }
      /**
       * <code>.gbuddy.Branch branch = 16;</code>
       */
      public Builder clearBranch() {  copyOnWrite();
        instance.clearBranch();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.Gym)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Gym();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "gymId_",
              "gymName_",
              "website_",
              "branch_",
            };
            String info =
                "\u0000\u0004\u0000\u0000\u0001\u0010\u0004\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0010\t";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Gym> parser = PARSER;
          if (parser == null) {
            synchronized (Gym.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Gym>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.Gym)
    private static final Gym DEFAULT_INSTANCE;
    static {
      Gym defaultInstance = new Gym();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Gym.class, defaultInstance);
    }

    public static Gym getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Gym> PARSER;

    public static com.google.protobuf.Parser<Gym> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface BranchOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.Branch)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 branchId = 1;</code>
     * @return The branchId.
     */
    int getBranchId();

    /**
     * <code>string locality = 2;</code>
     * @return The locality.
     */
    String getLocality();
    /**
     * <code>string locality = 2;</code>
     * @return The bytes for locality.
     */
    com.google.protobuf.ByteString
        getLocalityBytes();

    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    String getCity();
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    com.google.protobuf.ByteString
        getCityBytes();

    /**
     * <code>double latitude = 4;</code>
     * @return The latitude.
     */
    double getLatitude();

    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    double getLongitude();

    /**
     * <code>string contact = 6;</code>
     * @return The contact.
     */
    String getContact();
    /**
     * <code>string contact = 6;</code>
     * @return The bytes for contact.
     */
    com.google.protobuf.ByteString
        getContactBytes();
  }
  /**
   * Protobuf type {@code gbuddy.Branch}
   */
  public  static final class Branch extends
      com.google.protobuf.GeneratedMessageLite<
          Branch, Branch.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.Branch)
      BranchOrBuilder {
    private Branch() {
      locality_ = "";
      city_ = "";
      contact_ = "";
    }
    public static final int BRANCHID_FIELD_NUMBER = 1;
    private int branchId_;
    /**
     * <code>int32 branchId = 1;</code>
     * @return The branchId.
     */
    @Override
    public int getBranchId() {
      return branchId_;
    }
    /**
     * <code>int32 branchId = 1;</code>
     * @param value The branchId to set.
     */
    private void setBranchId(int value) {
      
      branchId_ = value;
    }
    /**
     * <code>int32 branchId = 1;</code>
     */
    private void clearBranchId() {
      
      branchId_ = 0;
    }

    public static final int LOCALITY_FIELD_NUMBER = 2;
    private String locality_;
    /**
     * <code>string locality = 2;</code>
     * @return The locality.
     */
    @Override
    public String getLocality() {
      return locality_;
    }
    /**
     * <code>string locality = 2;</code>
     * @return The bytes for locality.
     */
    @Override
    public com.google.protobuf.ByteString
        getLocalityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(locality_);
    }
    /**
     * <code>string locality = 2;</code>
     * @param value The locality to set.
     */
    private void setLocality(
        String value) {
      value.getClass();
  
      locality_ = value;
    }
    /**
     * <code>string locality = 2;</code>
     */
    private void clearLocality() {
      
      locality_ = getDefaultInstance().getLocality();
    }
    /**
     * <code>string locality = 2;</code>
     * @param value The bytes for locality to set.
     */
    private void setLocalityBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      locality_ = value.toStringUtf8();
      
    }

    public static final int CITY_FIELD_NUMBER = 3;
    private String city_;
    /**
     * <code>string city = 3;</code>
     * @return The city.
     */
    @Override
    public String getCity() {
      return city_;
    }
    /**
     * <code>string city = 3;</code>
     * @return The bytes for city.
     */
    @Override
    public com.google.protobuf.ByteString
        getCityBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(city_);
    }
    /**
     * <code>string city = 3;</code>
     * @param value The city to set.
     */
    private void setCity(
        String value) {
      value.getClass();
  
      city_ = value;
    }
    /**
     * <code>string city = 3;</code>
     */
    private void clearCity() {
      
      city_ = getDefaultInstance().getCity();
    }
    /**
     * <code>string city = 3;</code>
     * @param value The bytes for city to set.
     */
    private void setCityBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      city_ = value.toStringUtf8();
      
    }

    public static final int LATITUDE_FIELD_NUMBER = 4;
    private double latitude_;
    /**
     * <code>double latitude = 4;</code>
     * @return The latitude.
     */
    @Override
    public double getLatitude() {
      return latitude_;
    }
    /**
     * <code>double latitude = 4;</code>
     * @param value The latitude to set.
     */
    private void setLatitude(double value) {
      
      latitude_ = value;
    }
    /**
     * <code>double latitude = 4;</code>
     */
    private void clearLatitude() {
      
      latitude_ = 0D;
    }

    public static final int LONGITUDE_FIELD_NUMBER = 5;
    private double longitude_;
    /**
     * <code>double longitude = 5;</code>
     * @return The longitude.
     */
    @Override
    public double getLongitude() {
      return longitude_;
    }
    /**
     * <code>double longitude = 5;</code>
     * @param value The longitude to set.
     */
    private void setLongitude(double value) {
      
      longitude_ = value;
    }
    /**
     * <code>double longitude = 5;</code>
     */
    private void clearLongitude() {
      
      longitude_ = 0D;
    }

    public static final int CONTACT_FIELD_NUMBER = 6;
    private String contact_;
    /**
     * <code>string contact = 6;</code>
     * @return The contact.
     */
    @Override
    public String getContact() {
      return contact_;
    }
    /**
     * <code>string contact = 6;</code>
     * @return The bytes for contact.
     */
    @Override
    public com.google.protobuf.ByteString
        getContactBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(contact_);
    }
    /**
     * <code>string contact = 6;</code>
     * @param value The contact to set.
     */
    private void setContact(
        String value) {
      value.getClass();
  
      contact_ = value;
    }
    /**
     * <code>string contact = 6;</code>
     */
    private void clearContact() {
      
      contact_ = getDefaultInstance().getContact();
    }
    /**
     * <code>string contact = 6;</code>
     * @param value The bytes for contact to set.
     */
    private void setContactBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      contact_ = value.toStringUtf8();
      
    }

    public static Branch parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static Branch parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static Branch parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Branch parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Branch parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static Branch parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static Branch parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static Branch parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(Branch prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.Branch}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          Branch, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.Branch)
        BranchOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.Branch.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 branchId = 1;</code>
       * @return The branchId.
       */
      @Override
      public int getBranchId() {
        return instance.getBranchId();
      }
      /**
       * <code>int32 branchId = 1;</code>
       * @param value The branchId to set.
       * @return This builder for chaining.
       */
      public Builder setBranchId(int value) {
        copyOnWrite();
        instance.setBranchId(value);
        return this;
      }
      /**
       * <code>int32 branchId = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearBranchId() {
        copyOnWrite();
        instance.clearBranchId();
        return this;
      }

      /**
       * <code>string locality = 2;</code>
       * @return The locality.
       */
      @Override
      public String getLocality() {
        return instance.getLocality();
      }
      /**
       * <code>string locality = 2;</code>
       * @return The bytes for locality.
       */
      @Override
      public com.google.protobuf.ByteString
          getLocalityBytes() {
        return instance.getLocalityBytes();
      }
      /**
       * <code>string locality = 2;</code>
       * @param value The locality to set.
       * @return This builder for chaining.
       */
      public Builder setLocality(
          String value) {
        copyOnWrite();
        instance.setLocality(value);
        return this;
      }
      /**
       * <code>string locality = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearLocality() {
        copyOnWrite();
        instance.clearLocality();
        return this;
      }
      /**
       * <code>string locality = 2;</code>
       * @param value The bytes for locality to set.
       * @return This builder for chaining.
       */
      public Builder setLocalityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setLocalityBytes(value);
        return this;
      }

      /**
       * <code>string city = 3;</code>
       * @return The city.
       */
      @Override
      public String getCity() {
        return instance.getCity();
      }
      /**
       * <code>string city = 3;</code>
       * @return The bytes for city.
       */
      @Override
      public com.google.protobuf.ByteString
          getCityBytes() {
        return instance.getCityBytes();
      }
      /**
       * <code>string city = 3;</code>
       * @param value The city to set.
       * @return This builder for chaining.
       */
      public Builder setCity(
          String value) {
        copyOnWrite();
        instance.setCity(value);
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearCity() {
        copyOnWrite();
        instance.clearCity();
        return this;
      }
      /**
       * <code>string city = 3;</code>
       * @param value The bytes for city to set.
       * @return This builder for chaining.
       */
      public Builder setCityBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setCityBytes(value);
        return this;
      }

      /**
       * <code>double latitude = 4;</code>
       * @return The latitude.
       */
      @Override
      public double getLatitude() {
        return instance.getLatitude();
      }
      /**
       * <code>double latitude = 4;</code>
       * @param value The latitude to set.
       * @return This builder for chaining.
       */
      public Builder setLatitude(double value) {
        copyOnWrite();
        instance.setLatitude(value);
        return this;
      }
      /**
       * <code>double latitude = 4;</code>
       * @return This builder for chaining.
       */
      public Builder clearLatitude() {
        copyOnWrite();
        instance.clearLatitude();
        return this;
      }

      /**
       * <code>double longitude = 5;</code>
       * @return The longitude.
       */
      @Override
      public double getLongitude() {
        return instance.getLongitude();
      }
      /**
       * <code>double longitude = 5;</code>
       * @param value The longitude to set.
       * @return This builder for chaining.
       */
      public Builder setLongitude(double value) {
        copyOnWrite();
        instance.setLongitude(value);
        return this;
      }
      /**
       * <code>double longitude = 5;</code>
       * @return This builder for chaining.
       */
      public Builder clearLongitude() {
        copyOnWrite();
        instance.clearLongitude();
        return this;
      }

      /**
       * <code>string contact = 6;</code>
       * @return The contact.
       */
      @Override
      public String getContact() {
        return instance.getContact();
      }
      /**
       * <code>string contact = 6;</code>
       * @return The bytes for contact.
       */
      @Override
      public com.google.protobuf.ByteString
          getContactBytes() {
        return instance.getContactBytes();
      }
      /**
       * <code>string contact = 6;</code>
       * @param value The contact to set.
       * @return This builder for chaining.
       */
      public Builder setContact(
          String value) {
        copyOnWrite();
        instance.setContact(value);
        return this;
      }
      /**
       * <code>string contact = 6;</code>
       * @return This builder for chaining.
       */
      public Builder clearContact() {
        copyOnWrite();
        instance.clearContact();
        return this;
      }
      /**
       * <code>string contact = 6;</code>
       * @param value The bytes for contact to set.
       * @return This builder for chaining.
       */
      public Builder setContactBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setContactBytes(value);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.Branch)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new Branch();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "branchId_",
              "locality_",
              "city_",
              "latitude_",
              "longitude_",
              "contact_",
            };
            String info =
                "\u0000\u0006\u0000\u0000\u0001\u0006\u0006\u0000\u0000\u0000\u0001\u0004\u0002\u0208" +
                "\u0003\u0208\u0004\u0000\u0005\u0000\u0006\u0208";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<Branch> parser = PARSER;
          if (parser == null) {
            synchronized (Branch.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<Branch>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.Branch)
    private static final Branch DEFAULT_INSTANCE;
    static {
      Branch defaultInstance = new Branch();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        Branch.class, defaultInstance);
    }

    public static Branch getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<Branch> PARSER;

    public static com.google.protobuf.Parser<Branch> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }

  public interface LookupResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:gbuddy.LookupResponse)
      com.google.protobuf.MessageLiteOrBuilder {

    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    int getResponseCode();

    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    String getMessage();
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();

    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    java.util.List<MatchLookup>
        getLookupsList();
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    MatchLookup getLookups(int index);
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    int getLookupsCount();
  }
  /**
   * Protobuf type {@code gbuddy.LookupResponse}
   */
  public  static final class LookupResponse extends
      com.google.protobuf.GeneratedMessageLite<
          LookupResponse, LookupResponse.Builder> implements
      // @@protoc_insertion_point(message_implements:gbuddy.LookupResponse)
      LookupResponseOrBuilder {
    private LookupResponse() {
      message_ = "";
      lookups_ = emptyProtobufList();
    }
    public static final int RESPONSECODE_FIELD_NUMBER = 1;
    private int responseCode_;
    /**
     * <code>int32 responseCode = 1;</code>
     * @return The responseCode.
     */
    @Override
    public int getResponseCode() {
      return responseCode_;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     * @param value The responseCode to set.
     */
    private void setResponseCode(int value) {
      
      responseCode_ = value;
    }
    /**
     * <code>int32 responseCode = 1;</code>
     */
    private void clearResponseCode() {
      
      responseCode_ = 0;
    }

    public static final int MESSAGE_FIELD_NUMBER = 2;
    private String message_;
    /**
     * <code>string message = 2;</code>
     * @return The message.
     */
    @Override
    public String getMessage() {
      return message_;
    }
    /**
     * <code>string message = 2;</code>
     * @return The bytes for message.
     */
    @Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      return com.google.protobuf.ByteString.copyFromUtf8(message_);
    }
    /**
     * <code>string message = 2;</code>
     * @param value The message to set.
     */
    private void setMessage(
        String value) {
      value.getClass();
  
      message_ = value;
    }
    /**
     * <code>string message = 2;</code>
     */
    private void clearMessage() {
      
      message_ = getDefaultInstance().getMessage();
    }
    /**
     * <code>string message = 2;</code>
     * @param value The bytes for message to set.
     */
    private void setMessageBytes(
        com.google.protobuf.ByteString value) {
      checkByteStringIsUtf8(value);
      message_ = value.toStringUtf8();
      
    }

    public static final int LOOKUPS_FIELD_NUMBER = 17;
    private com.google.protobuf.Internal.ProtobufList<MatchLookup> lookups_;
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    @Override
    public java.util.List<MatchLookup> getLookupsList() {
      return lookups_;
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    public java.util.List<? extends MatchLookupOrBuilder>
        getLookupsOrBuilderList() {
      return lookups_;
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    @Override
    public int getLookupsCount() {
      return lookups_.size();
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    @Override
    public MatchLookup getLookups(int index) {
      return lookups_.get(index);
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    public MatchLookupOrBuilder getLookupsOrBuilder(
        int index) {
      return lookups_.get(index);
    }
    private void ensureLookupsIsMutable() {
      com.google.protobuf.Internal.ProtobufList<MatchLookup> tmp = lookups_;
      if (!tmp.isModifiable()) {
        lookups_ =
            com.google.protobuf.GeneratedMessageLite.mutableCopy(tmp);
       }
    }

    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void setLookups(
        int index, MatchLookup value) {
      value.getClass();
  ensureLookupsIsMutable();
      lookups_.set(index, value);
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void addLookups(MatchLookup value) {
      value.getClass();
  ensureLookupsIsMutable();
      lookups_.add(value);
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void addLookups(
        int index, MatchLookup value) {
      value.getClass();
  ensureLookupsIsMutable();
      lookups_.add(index, value);
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void addAllLookups(
        Iterable<? extends MatchLookup> values) {
      ensureLookupsIsMutable();
      com.google.protobuf.AbstractMessageLite.addAll(
          values, lookups_);
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void clearLookups() {
      lookups_ = emptyProtobufList();
    }
    /**
     * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
     */
    private void removeLookups(int index) {
      ensureLookupsIsMutable();
      lookups_.remove(index);
    }

    public static LookupResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LookupResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LookupResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LookupResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LookupResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data);
    }
    public static LookupResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, data, extensionRegistry);
    }
    public static LookupResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LookupResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LookupResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input);
    }
    public static LookupResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
    }
    public static LookupResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input);
    }
    public static LookupResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageLite.parseFrom(
          DEFAULT_INSTANCE, input, extensionRegistry);
    }

    public static Builder newBuilder() {
      return (Builder) DEFAULT_INSTANCE.createBuilder();
    }
    public static Builder newBuilder(LookupResponse prototype) {
      return (Builder) DEFAULT_INSTANCE.createBuilder(prototype);
    }

    /**
     * Protobuf type {@code gbuddy.LookupResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageLite.Builder<
          LookupResponse, Builder> implements
        // @@protoc_insertion_point(builder_implements:gbuddy.LookupResponse)
        LookupResponseOrBuilder {
      // Construct using com.example.gym.buddies.data.protos.MatchLookupProto.LookupResponse.newBuilder()
      private Builder() {
        super(DEFAULT_INSTANCE);
      }


      /**
       * <code>int32 responseCode = 1;</code>
       * @return The responseCode.
       */
      @Override
      public int getResponseCode() {
        return instance.getResponseCode();
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @param value The responseCode to set.
       * @return This builder for chaining.
       */
      public Builder setResponseCode(int value) {
        copyOnWrite();
        instance.setResponseCode(value);
        return this;
      }
      /**
       * <code>int32 responseCode = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearResponseCode() {
        copyOnWrite();
        instance.clearResponseCode();
        return this;
      }

      /**
       * <code>string message = 2;</code>
       * @return The message.
       */
      @Override
      public String getMessage() {
        return instance.getMessage();
      }
      /**
       * <code>string message = 2;</code>
       * @return The bytes for message.
       */
      @Override
      public com.google.protobuf.ByteString
          getMessageBytes() {
        return instance.getMessageBytes();
      }
      /**
       * <code>string message = 2;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          String value) {
        copyOnWrite();
        instance.setMessage(value);
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        copyOnWrite();
        instance.clearMessage();
        return this;
      }
      /**
       * <code>string message = 2;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        copyOnWrite();
        instance.setMessageBytes(value);
        return this;
      }

      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      @Override
      public java.util.List<MatchLookup> getLookupsList() {
        return java.util.Collections.unmodifiableList(
            instance.getLookupsList());
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      @Override
      public int getLookupsCount() {
        return instance.getLookupsCount();
      }/**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      @Override
      public MatchLookup getLookups(int index) {
        return instance.getLookups(index);
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder setLookups(
          int index, MatchLookup value) {
        copyOnWrite();
        instance.setLookups(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder setLookups(
          int index, MatchLookup.Builder builderForValue) {
        copyOnWrite();
        instance.setLookups(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder addLookups(MatchLookup value) {
        copyOnWrite();
        instance.addLookups(value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder addLookups(
          int index, MatchLookup value) {
        copyOnWrite();
        instance.addLookups(index, value);
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder addLookups(
          MatchLookup.Builder builderForValue) {
        copyOnWrite();
        instance.addLookups(builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder addLookups(
          int index, MatchLookup.Builder builderForValue) {
        copyOnWrite();
        instance.addLookups(index,
            builderForValue.build());
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder addAllLookups(
          Iterable<? extends MatchLookup> values) {
        copyOnWrite();
        instance.addAllLookups(values);
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder clearLookups() {
        copyOnWrite();
        instance.clearLookups();
        return this;
      }
      /**
       * <code>repeated .gbuddy.MatchLookup lookups = 17;</code>
       */
      public Builder removeLookups(int index) {
        copyOnWrite();
        instance.removeLookups(index);
        return this;
      }

      // @@protoc_insertion_point(builder_scope:gbuddy.LookupResponse)
    }
    @Override
    @SuppressWarnings({"unchecked", "fallthrough"})
    protected final Object dynamicMethod(
        MethodToInvoke method,
        Object arg0, Object arg1) {
      switch (method) {
        case NEW_MUTABLE_INSTANCE: {
          return new LookupResponse();
        }
        case NEW_BUILDER: {
          return new Builder();
        }
        case BUILD_MESSAGE_INFO: {
            Object[] objects = new Object[] {
              "responseCode_",
              "message_",
              "lookups_",
              MatchLookup.class,
            };
            String info =
                "\u0000\u0003\u0000\u0000\u0001\u0011\u0003\u0000\u0001\u0000\u0001\u0004\u0002\u0208" +
                "\u0011\u001b";
            return newMessageInfo(DEFAULT_INSTANCE, info, objects);
        }
        // fall through
        case GET_DEFAULT_INSTANCE: {
          return DEFAULT_INSTANCE;
        }
        case GET_PARSER: {
          com.google.protobuf.Parser<LookupResponse> parser = PARSER;
          if (parser == null) {
            synchronized (LookupResponse.class) {
              parser = PARSER;
              if (parser == null) {
                parser =
                    new DefaultInstanceBasedParser<LookupResponse>(
                        DEFAULT_INSTANCE);
                PARSER = parser;
              }
            }
          }
          return parser;
      }
      case GET_MEMOIZED_IS_INITIALIZED: {
        return (byte) 1;
      }
      case SET_MEMOIZED_IS_INITIALIZED: {
        return null;
      }
      }
      throw new UnsupportedOperationException();
    }


    // @@protoc_insertion_point(class_scope:gbuddy.LookupResponse)
    private static final LookupResponse DEFAULT_INSTANCE;
    static {
      LookupResponse defaultInstance = new LookupResponse();
      // New instances are implicitly immutable so no need to make
      // immutable.
      DEFAULT_INSTANCE = defaultInstance;
      com.google.protobuf.GeneratedMessageLite.registerDefaultInstance(
        LookupResponse.class, defaultInstance);
    }

    public static LookupResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static volatile com.google.protobuf.Parser<LookupResponse> PARSER;

    public static com.google.protobuf.Parser<LookupResponse> parser() {
      return DEFAULT_INSTANCE.getParserForType();
    }
  }


  static {
  }

  // @@protoc_insertion_point(outer_class_scope)
}
